### ISSUE TITLE
Kwc_User_Activate for frontend does not work

### ISSUE THREAD

**Issue by Ben-Ho** [koala-framework/koala-framework#209]
Doesn't work in 3.7 because success=true is returned for ajax-request.
In 3.4 ajax-request also failed but success=false is returned so it worked.

Ajax request failing because "code" parameter isn't sent but set as url-param so post does work.

Possible fix:
forward "code" param from get-Params in hiddenfield "config" via getTemplateVars

**Comment by yacon** [comment]
?

**Comment by Ben-Ho** [comment]
I don't think it is already solved...

**Comment by nsams** [comment]
solved in sso branch
