### ISSUE TITLE
PHPExcel is requred library (errors)

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#286]
Hi!

Standard Excel-grid unloading not works with adding phpexcel library:

*<b>Fatal error</b>:  Class 'PHPExcel' not found in <b>/var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action/Auto/Grid.php</b> on line <b>931</b><br />*

Line 931:
```
$xls = new PHPExcel();
```

My composer:
```
{
    "require": {
         "koala-framework/koala-framework": "3.8.x-dev",
	  "phpoffice/phpexcel": "1.8.0"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```
Library exists in vendor folder. Library string also exists in autoload_namespaces.php file.

You can simply check this issue by adding this line to **IndexController.php** of **kwf-app-demo**:
```
$xls = new PHPExcel();
```

p.s. Now my Excel unloadings works only with old KWF 3.5 line in config.ini:
```
externLibraryPath.phpexcel = ./vendor/phpoffice/phpexcel/Classes
```

**Comment by nsams** [comment]
Probably related with 4a2a5a6a

**Comment by Sogl** [comment]
>Probably related with 4a2a5a6
What this mean? =)

Can I do something to help?

**Comment by yacon** [comment]
Yes you were right..
I created a pull request for this issue: #294

**Comment by nsams** [comment]
fixed...

**Comment by Sogl** [comment]
Nice! Thank you! =)
