### ISSUE TITLE
"Error - wrong version" loop problem

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#287]
Hi!

KWF 3.8 has a "error - wrong version" loop problem.

See:
![wrong](https://cloud.githubusercontent.com/assets/7556290/6034056/c95d217a-ac69-11e4-824b-aea289429596.jpg) 

Only one way to solve this problem - clear browser cache (or Ctrl + F5 but doesn't always help).

For example, if I change bootstrap.php in root dir (with text "site unavailable now") and change to normal after works - this dialog shows to all users and I go to clean them browser cache =) In general, this error occurs after any changes in the files of my application

Button "OK" reload page and error shows again.

**Comment by nsams** [comment]
I'm aware of one way to reproduce this: If you reload the page *while* build is running. (Though not always)

Is this also the case for you?
If not - do you see a pattern how it's to reproduce?

**Comment by Sogl** [comment]
>I'm aware of one way to reproduce this: If you reload the page while build is running. (Though not always)

No. When I develop locally - same problem exists. I'm not reload page in build time for sure :D

>Is this also the case for you?

Yes. Every time if I update my app - this error shows to all app users and OK button not helps.

>If not - do you see a pattern how it's to reproduce?

1. Change something in controllers or js
2. build and clear-cache
3. Loop problem (90% cases)

**Comment by nsams** [comment]
Ok, I see.

Windows with WAMP, right?

Can you also reproduce the problem with unchanged kwf-app-demo?

**Comment by Sogl** [comment]
>Windows with WAMP, right? 

And on Linux. My production server based on Linux system and has this problem too. 

>Can you also reproduce the problem with unchanged kwf-app-demo?

Just did it on WAMP:
1. Add to IndexController.php one line:
```
$xls = 1;
```
2. build and clear-cache
3. Loop problem

**Comment by Sogl** [comment]
I found that you don't need any changes in file. Just build and clear-cache and problem shows to you.

**Comment by nsams** [comment]
Please test, if that didn't help I'll reopen.

**Comment by Sogl** [comment]
Just tested.
Still the same error.

What i did:
1. composer update
2. php bootstrap.php build
3. php bootstrap.php clear-cache
4. loop problem =(

**Comment by nsams** [comment]
Finally, I can reproduce.

Problem is caused by clear-cache *after* build.

Two workarounds:

- clear browser cache (or reload with ctrl+shift+r)
- clear-cache before build

...and I'm working on a fix.

**Comment by Sogl** [comment]
Good news.
I need working OK button (correctly cache clearing) =)
