### ISSUE TITLE
Firefox overflow scrolls problem

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#288]
Hi!

If height of the form is less than height of all elements in it, a horizontal and vertical scrolls shows. In 3.5 ONLY vertical scroll shows.
I increase height and most of problems is gone.

eg call:
```
$this->_editDialog = array(
                                       'controllerUrl' => '/flightplans/flightfile',
                                       'width' => 550,
                                       'height' => 270  <--- this value must be more than height of all elements on form
                                       );
```

eg. adding field:
```
$this->_form->add(new Kwf_Form_Field_Select('typeId', trlKwf('Type')))
        ->setValues($typeModel)
        ->setSelect($typeSelect)
        ->setWidth(400)
        ->setAllowBlank(false);
```

But one problem is solved only by comment set of width line.
It exists also in version 3.5.

See:
![3 5_edit_dropdown_bug](https://cloud.githubusercontent.com/assets/7556290/6034114/9f86975e-ac6a-11e4-9903-425cc433fbfc.jpg)
Scrolls not shows, but part of dropdown is hidden.

In 3.8 it looks like:
![3 8_edit_dropdown_bug](https://cloud.githubusercontent.com/assets/7556290/6034116/ab64af5c-ac6a-11e4-83b9-91e6c3b9e755.jpg)

eg.:
```
$positions = new Kwf_Form_Field_Select('positionId', trlKwf('Position'));
        $positions->setValues($typeModel->getRows($typeSelect));
        $positions->setAllowBlank(false);
        $positions->setWidth(400);
```

I created a small testcase based on kwf-app-demo to show you this bug:
https://github.com/Sogl/kwf-app-demo
Just click on edit dialog in FF.

And also I found why the most scrolls problem happened... 

Scrolls shows only in Firefox, see:
```
.ext2-gecko .x2-window-body .x2-form-item {
    overflow: auto;
}
```
Every form item has this class and (overflow: auto) fires on each and adds scrolls. Please fix it =)

**Comment by nsams** [comment]
This is how it looks for me:
![ph2](https://cloud.githubusercontent.com/assets/50764/6065505/2b4bf288-ad66-11e4-92bd-3ecf48587ee4.png)

the scroll bars go away if I make the window wider (or the combo boxes narrower)

please create a better test case or tell me where exactly to click...

**Comment by Sogl** [comment]
>the scroll bars go away if I make the window wider (or the combo boxes narrower)

That's right. If you see this test in Chrome - only vertical scroll is appear.
