### ISSUE TITLE
Not a complete translation

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#290]
Hi!
I use RU translation, but it not full. I did full RU translation pull request before.

1. Delete dialog.
kwf-lib/trl.xml has yes/no translation to RU, but shows me EN.
See:
![delete](https://cloud.githubusercontent.com/assets/7556290/6034328/3774e802-ac6d-11e4-85dd-d5d30448f1a6.jpg)

2. "Loading..." text in controllers.
First time shows me translated version, second and other times - EN version.
See:
![loading](https://cloud.githubusercontent.com/assets/7556290/6034408/f5996394-ac6d-11e4-868d-ecfb04d89361.jpg)

3. Filtering.
See:
![filter](https://cloud.githubusercontent.com/assets/7556290/6034364/8e05ec7a-ac6d-11e4-9602-abc651116ab3.JPG)

4. Pagination.
See:
![pagination](https://cloud.githubusercontent.com/assets/7556290/6034379/9fe3a5f4-ac6d-11e4-9731-c7070b8623e8.JPG)

5. Calendar.
See:
![calendar](https://cloud.githubusercontent.com/assets/7556290/6034446/5a99b3b6-ac6e-11e4-82e8-93332cb11870.JPG)
Also it would be nice to change first day of the week.

P.S.
I found file related to translation problem (pagination):
\vendor\koala-framework\koala-framework\extjs2\src\widgets\PagingToolbar.js

if I change values to needed lang - all is OK.

Also I found why it happened (maybe). I use **webCodeLanguage = ru**, but file with translations has 'en' prefix:
\vendor\koala-framework\koala-framework\Ext\ext-lang-en.js

That's why in previous version all be OK. **webCodeLanguage** was **en** in 3.5.
I think I need ext-lang-ru.js file.
Is it right?

**Comment by yacon** [comment]
Should be fixed now in the latest 3.8. Can you give it a try?

**Comment by Sogl** [comment]
Thank you, yacon! 
Everything looks fine now.

**Comment by Sogl** [comment]
Some more:

1. User rights default admin name:
![rights](https://cloud.githubusercontent.com/assets/7556290/7673070/46128cfc-fd4e-11e4-8e4b-6a3f893c5c6f.JPG)

2. Generate new activation link:
![generate](https://cloud.githubusercontent.com/assets/7556290/7673073/5459822a-fd4e-11e4-8221-16f8d048980e.JPG)

**Comment by nsams** [comment]
1. is fixed with efed0a88c0c09c376f5cf02a6b17c7beb5daafd3

2. added with 2dae1d6e8e003c73bceaf4cb529c534282f4559d to trl.xml

**Comment by Sogl** [comment]
>added with 2dae1d6 to trl.xml

I added <ru> strings in my local copy (https://github.com/koala-framework/koala-framework/pull/345), clear-cache and build, but this string not translate. Maybe trlKwf is missing?

**Comment by nsams** [comment]
Try deleting `AppData/Local/Temp/kwf-uglifyjs` and build again.

Does that help?

**Comment by Sogl** [comment]
I don't have this folder in Temp.

**Comment by nsams** [comment]
Well, it is somewhere, probably AppData is hidden or something.

I looked this path up on windows 8.1

**Comment by Sogl** [comment]
That's because my WAMP is portable. My path is `C:\OpenServer\userdata\temp`

After delete build is so sloooowly and show me error:
```
c:\OpenServer\domains\aviashelf>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing koala-framework/extjs2 (v2.3.0-p5)
  - Installing koala-framework/extjs2 (v2.3.0-p6)
    Downloading: 100%

  - Updating koala-framework/koala-framework 3.8.x-dev (e4f8e83 => d547fd4)
    Checking out d547fd49a7da2a49838b8cb947af58eb5ec49a63

Writing lock file
Generating autoload files

installing npm dependencies in 'C:\OpenServer\domains\aviashelf/vendor/koala-framework/koala-framework'...

installing bower dependencies...

c:\OpenServer\domains\aviashelf>php bootstrap.php clear-cache
[ 1/10] clearing simpleCache... OK (1ms)
[ 2/10] clearing model......... OK (5ms)
[ 3/10] clearing simple........ OK (24ms)
[ 4/10] clearing twig.......... OK (1ms)
[ 5/10] clearing zend.......... OK (1ms)
[ 6/10] clearing config........ OK (1ms)
[ 7/10] clearing setup......... OK (1ms)
[ 8/10] clearing assets........ OK (21ms)
[9/10] refreshing config...... OK (15ms)
[10/10] refreshing setup....... OK (198ms)

c:\OpenServer\domains\aviashelf>php bootstrap.php build
[ 1/3] building trl...... OK (77ms)
[ 2/3] building events... OK (235ms)
[ 3/3] building assets...
calculating dependencies...
100% [#####################] Maintenance printcss
compiling assets...
 42% [#########------------] web/js/Actiongrid.js                              exception 'ErrorException' with message 'file_put_contents(c:\openserver\userdata\temp/kwf-uglifyjs/web/js/Actiongrid.js.50ee0a29cc79a86d26ecebdc15c3a599.min.js): failed to open stream: Invalid argument' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\sourcemaps\Kwf\SourceMaps\SourceMap.php:591
Stack trace:
#0 [internal function]: Kwf_Debug::handleError(2, 'file_put_conten...', 'C:\\OpenServer\\d...', 591, Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\sourcemaps\Kwf\SourceMaps\SourceMap.php(591): file_put_contents('c:\\openserver\\u...', '')
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Dependency\File\Js.php(61): Kwf_SourceMaps_SourceMap->save('c:\\openserver\\u...', 'c:\\openserver\\u...')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(168): Kwf_Assets_Dependency_File_Js->warmupCaches()
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(15): Kwf_Util_Build_Types_Assets->_build(Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_Build_Types_Abstract->build(Array)
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildController.php(35): Kwf_Util_Build->build(Array)
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Cli_BuildController->indexAction()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#11 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#12 {main} [ERROR] (216344ms)

c:\OpenServer\domains\aviashelf>
```

**Comment by nsams** [comment]
yes, it's slow as build has to re-run uglifyjs for every js file (as you deleted the cache files)

does the error persist? it simpy tries to write a file into kwf-uglifyjs - seems the relevant folder doesn't exist (but that should be created automatically)

**Comment by Sogl** [comment]
On my windows 7 x64 build well after deleting files in "kwf-uglifyjs". 
But after second build I can't see RU translation.

**Comment by nsams** [comment]
some cache is very annoying here...

delete the following manually:

    build
    cache/*/*
    kwf-uglifyjs (again)

**Comment by Sogl** [comment]
Hm, same error on my home Windows 8.1 machine. I try run my server with "Run as administrator"... strange problem, I can't see it before.

**Comment by Sogl** [comment]
Found a way how to build my app on Windows 8.1. 
If build breaks on file - open folder contains it and delete 3 files with this name. Then build again and do it till finish.
Horrible, but working =)
