### ISSUE TITLE
xls to xlsx migration

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#295]
Hi!

Why KWF still uses oldschool format *.xls (excel 2003) with PHPExcel library? Are there some difficulties in the transition to the new format?

In my own extended classes I rewrite writer from Excel5 to Excel2007 and everything works fine.

**Comment by nsams** [comment]
well, not every client is capable of reading xlsx. Probably nowadays this is not true anymore...

any problems you have with xls that could be solved by using xlsx?

**Comment by Sogl** [comment]
If you use large Excel templates difference in file size can be up to 3 times.

Can also be a problem with formatting that Excel 2003 does not support.
![excel](https://cloud.githubusercontent.com/assets/7556290/6059308/ae9eca60-ad7b-11e4-840b-386445d2394c.jpg)


p.s. Lately I've never see Microsoft Office 2003 :D

**Comment by nsams** [comment]
Ok, you are right... why not change it...

could you create a pull request for that change?

**Comment by Sogl** [comment]
>could you create a pull request for that change?
Done.
https://github.com/koala-framework/koala-framework/pull/298

But I change writer and extension ONLY, not going deeper...for me this change works.

**Comment by nsams** [comment]
fixed with ebf5ac1f87988a174a585cf3e4725b2e4dd30200
