### ISSUE TITLE
multiselect rows in Grid

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#296]
Hi!

How to do it? Especially for deleting rows.
CTRL and SHIFT not works....

**Comment by nsams** [comment]
You need a selection model that supports multiple selections I think...

**Comment by yacon** [comment]
You need to write your own xtype as descriped here: http://www.koala-framework.org/documentation/kwf_general_features/autoform_autogrid/custom_form_grid_class
You also have to set a selModel in your gridConfig.
An example grid panel would look like that:
var fooGrid = new Kwf.Auto.GridPanel({
        controllerUrl: '/admin/foo/bar',
        region: 'center',
        title: 'Amazing Grid',
        gridConfig: {
            selModel: new Ext.grid.CheckboxSelectionModel()
        }
});

**Comment by nsams** [comment]
please re-open if that doesn't work

**Comment by Sogl** [comment]
>You also have to set a selModel in your gridConfig.

Tried to add this piece of code to my grid:
```javascript
var Employees = Ext2.extend(Ext2.Panel,
{
    initComponent : function(test)
    {
        var passport = new Kwf.Auto.GridPanel({
             controllerUrl   : '/staffs/staffdocuments',
             collapsible     : true,
             stripeRows      : true,
             title           : trl('Документы'),
             gridConfig: {
                selModel: new Ext2.grid.CheckboxSelectionModel()
             }
        });
       
       ...etc
```

And error in result:
```javascript
TypeError: Ext2.grid.CheckboxSelectionModel is not a constructor
...e:trl("Документы"),gridConfig:{selModel:new Ext2.grid.CheckboxSelectionModel}});...
-------------------------------------------^
```

**Comment by nsams** [comment]
you need to have the required asset dependency for CheckboxSelectionModel.

add ExtGridCheckboxSelectionModel in dependencies.ini

**Comment by Sogl** [comment]
It works, but how to show checkboxes only when `Delete` button is present? Some app roles don't have permissions (changed in controller) to delete rows and they don't need to see checkboxes in grid.

**Comment by nsams** [comment]
Simplest would be to pass in to the grid a config option that enabled/disables this selModel.

        var gridConfig = {};
        if (this.showCheckboxSelection) {
                gridConfig.selModel = new Ext2.grid.CheckboxSelectionModel();
        }
        var passport = new Kwf.Auto.GridPanel({
             controllerUrl   : '/staffs/staffdocuments',
             collapsible     : true,
             stripeRows      : true,
             title           : trl('Документы'),
             gridConfig: gridConfig
        });

then you have to correctly pass showCheckboxSelection into the panel when constructing it

**Comment by Sogl** [comment]
@nsams But how to pass `showCheckboxSelection` value from php to js and where?
These lines:
```
protected function _initColumns()
    {
        parent::_initColumns();
        $this->showCheckboxSelection = true;
```
not working.
