### ISSUE TITLE
Limit the user log to one month

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#299]
Hi!

In my app logs stored since the release app in production in table 'kwf_user_messages'. How can I limit this DB rows to one month?

**Comment by nsams** [comment]
I would create a cron job that deletes older messages. Are those messages really too many for you?

**Comment by Sogl** [comment]
>Are those messages really too many for you?

Not so much, just for viewing pleasure =)

I thought it was somehow possible to limit in KWF core.

**Comment by nsams** [comment]
No, that is not possible - it's sorted by date and has paging - so not really a problem if you have many entries.
