### ISSUE TITLE
How to call json-xls from custom dropdown

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#302]
Hi!

I want to create dropdown menu with these things:
1. Click to dropdown menu creates modal dialog. Modal dialog contains two dates and button OK.
2. Button OK send dates to 'json-xls' (excel export)
2. Custom excel template per menu item. Data loads to selected excel-file.

First step I want only to call standart 'json-xls' from my view:
```javascript
var Exceluploads = Ext2.extend(Ext2.Panel, {
	timeout: 300000,

    initComponent : function(test) {

        var employeeWorks = new Kwf.Auto.GridPanel({
			controllerUrl   : '/exceluploads/exceluploads',
			region          : 'center',
			height          : 600,
			resizable       : true,
			split           : true,
			title           : trl('Данные по сотрудникам'),
			gridConfig: {
				tbar: [
					//'->',
					{
						text:'Выгрузки',
						icon: '/assets/silkicons/page_excel.png',
						cls: 'x2-btn-text-icon',
						menu: [{
							text:'Выгрузка EXXON',
							icon: '/assets/silkicons/page_excel.png',
							cls: 'x2-btn-text-icon',
							handler : this.onXls
						},{
							text:'Выгрузка SEIC',
							icon: '/assets/silkicons/page_excel.png',
							cls: 'x2-btn-text-icon',
							handler : this.onXls
						}
						]
					},
				]
			}
        });

        var grid = new Kwf.Auto.GridPanel({
            controllerUrl   : '/exceluploads/months',
            region          : 'west',
            width           : 200,
            resizable       : true,
            split           : true,
            collapsible     : true,
            bindings: [{
                        queryParam: 'workId',
                        item: employeeWorks
                      }],
            title           : trlKwf('Calendar'),
        });

       this.layout = 'border';
       this.items = [grid, {
                     layout: 'border',
                     region: 'center',
                     items: [employeeWorks]
                     }];
        Exceluploads.superclass.initComponent.call(this);
    },

	onXls : function() {
        var params = Kwf.clone(this.getStore().baseParams);
        if(this.getStore().sortInfo){
            var pn = this.getStore().paramNames;
            params[pn["sort"]] = this.getStore().sortInfo.field;
            params[pn["dir"]] = this.getStore().sortInfo.direction;
        }

        Ext2.Ajax.request({
            url : this.controllerUrl+'/json-xls',
            params  : params,
            timeout: 600000, // 10 minuten
            progress: true,
            progressTitle : trlKwf('Excel export'),
            success: function(response, opt, r) {
                var downloadUrl = this.controllerUrl+'/download-export-file?downloadkey='+r.downloadkey;
                for (var i in params) {
                    downloadUrl += '&' + i + '=' + params[i];
                }
                if (Ext2.isIE) {
                    Ext2.Msg.show({
                        title: trlKwf('Your download is ready'),
                        msg: trlKwf('Please click on the following link to download your Excel file.')
                            +'<br /><br />'
                            +'<a class="xlsExportLink" href="'+downloadUrl+'" target="_blank">'
                            +trlKwf('Excel export file')+'</a>',
                        icon: Ext2.Msg.INFO,
                        buttons: { ok: trlKwf('Close') }
                    });
                } else {
                    Ext2.getBody().createChild({
                        html: '<iframe width="0" height="0" src="'+downloadUrl+'"></iframe>'
                    });
                }
            },
            scope: this
        });
    }

});
```

Now I see error:
```
TypeError: this.getStore is not a function
...},onXls:function(){var params=Kwf.clone(this.getStore().baseParams);if(this.getS...
```

As I understand, I need to also migrate this function...
I chose the right way to implement? May have an easier way?

How it looks now:
![tbar2](https://cloud.githubusercontent.com/assets/7556290/6166290/b1c30ccc-b2fa-11e4-8e83-504b0bc592e1.jpg)

**Comment by nsams** [comment]
When defining the  `handler : this.onXls` you are missing `scope: this`. That's why this.getStore doesn't work in `onXls`.

Other than that it should work if you implement everything needed...
You may even create your own `jsonXlsAction` in the controller that does completely custom stuff (if needed)

**Comment by Sogl** [comment]
>When defining the handler : this.onXls you are missing scope: this. That's why this.getStore doesn't work in onXls.

Same error after this change.

**Comment by nsams** [comment]
Ok, if you need my help on this I need to have a look myself. Please push a testcase (preferrable based on kwf-app-demo) somewhere.

**Comment by Sogl** [comment]
Done.
https://github.com/Sogl/kwf-app-demo

Please take a look at what the problem is.

**Comment by nsams** [comment]
your problem is that `this` is not the grid, it's a Members object. To export you need to access the grid, like so:

    diff --git a/js/Members.js b/js/Members.js                                                                                                                      
    index 44dbd54..05d60ed 100755                                                                                                                                   
    --- a/js/Members.js                                                                                                                                             
    +++ b/js/Members.js                                                                                                                                             
    @@ -17,7 +17,7 @@ var Members = Ext2.extend(Ext2.Panel,                                                                                                         
                title           : trl('Contacts')                                                                                                                  
            });                                                                                                                                                    
                                                                                                                                                                    
    -        var grid = new Kwf.Auto.GridPanel({                                                                                                                    
    +        this.membersGrid = new Kwf.Auto.GridPanel({                                                                                                            
                controllerUrl   : '/members/members',                                                                                                              
                region          : 'west',                                                                                                                          
                width           : 700,                                                                                                                             
    @@ -36,12 +36,14 @@ var Members = Ext2.extend(Ext2.Panel,                                                                                                       
                                text:'Выгрузка EXXON',                                                                                                             
                                icon: '/assets/silkicons/page_excel.png',                                                                                          
                                cls: 'x2-btn-text-icon',                                                                                                           
    -                            handler : this.onXls                                                                                                               
    +                            handler : this.onXls,                                                                                                              
    +                            scope: this                                                                                                                        
                            },{                                                                                                                                    
                                text:'Выгрузка SEIC',                                                                                                              
                                icon: '/assets/silkicons/page_excel.png',                                                                                          
                                cls: 'x2-btn-text-icon',                                                                                                           
    -                            handler : this.onXls                                                                                                               
    +                            handler : this.onXls,                                                                                                              
    +                            scope: this                                                                                                                        
                            }                                                                                                                                      
                            ]                                                                                                                                      
                        },
    @@ -54,7 +56,7 @@ var Members = Ext2.extend(Ext2.Panel,
            });
    
            this.layout = 'border';
    -        this.items = [grid, {
    +        this.items = [this.membersGrid, {
                layout: 'border',
                region: 'center',
                items: [form, contacts]
    @@ -63,21 +65,22 @@ var Members = Ext2.extend(Ext2.Panel,
        },
    
        onXls : function() {
    -        var params = Kwf.clone(this.getStore().baseParams);
    -        if(this.getStore().sortInfo){
    -            var pn = this.getStore().paramNames;
    -            params[pn["sort"]] = this.getStore().sortInfo.field;
    -            params[pn["dir"]] = this.getStore().sortInfo.direction;
    +        var grid = this.membersGrid;
    +        var params = Kwf.clone(grid.getStore().baseParams);
    +        if(grid.getStore().sortInfo){
    +            var pn = grid.getStore().paramNames;
    +            params[pn["sort"]] = grid.getStore().sortInfo.field;
    +            params[pn["dir"]] = grid.getStore().sortInfo.direction;
            }
    
            Ext2.Ajax.request({
    -            url : this.controllerUrl+'/json-xls',
    +            url : grid.controllerUrl+'/json-xls',
                params  : params,
                timeout: 600000, // 10 minuten
                progress: true,
                progressTitle : trlKwf('Excel export'),
                success: function(response, opt, r) {
    -                var downloadUrl = this.controllerUrl+'/download-export-file?downloadkey='+r.downloadkey;
    +                var downloadUrl = grid.controllerUrl+'/download-export-file?downloadkey='+r.downloadkey;
                    for (var i in params) {
                        downloadUrl += '&' + i + '=' + params[i];
                    }


Or, alternatively you could create a new class inheriting `Kwf.Auto.GridPanel` where you place the onXls method - there this is your grid.

**Comment by Sogl** [comment]
Niko, thank you!

Now how can I use xlsx template per menu item? I need to transfer button id or something else from js to php `jsonXlsAction`.

**Comment by nsams** [comment]
> Now how can I use xlsx template per menu item? I need to transfer button id or something else from js to php jsonXlsAction.

- You can create two onXls methods and call two different actions
- you can create two onXls methods and pass a parameter using `params`
- in the onXls method you get a event object passed, I'm pretty sure you can find out the clicked button using that

**Comment by Sogl** [comment]
I try to do this with function. But how can I show button text?

I tried with `console.log(tbar.text);` and with `console.log(tbar.menu.text);` but it doesn't work =(

Eg:
```javascript
menu: [{
			text:'Выгрузка EXXON',
			icon: '/assets/silkicons/page_excel.png',
			cls: 'x2-btn-text-icon',
			//handler : this.onItemClick,
                        handler: function() {
                                Ext2.MessageBox.alert('1');

                                console.log(tbar.text);

                                console.log(tbar.menu.text);
                            },
                            scope: this
		},
```

**Comment by nsams** [comment]
the handler gets passed an event object, there you'll find the text.

However you don't need to do that - as you are defining the handler fir the 'Выгрузка EXXON' button - you know exaclty what button that handler belongs to!

you could even call this.onXls('foo') and in the other button handler this.onXls('bar')

**Comment by Sogl** [comment]
>However you don't need to do that - as you are defining the handler fir the 'Выгрузка EXXON' button - you know exaclty what button that handler belongs to!

Ok, but I can't understand how to get this button text in OnXls function =(

Now I change handler to this (different values, as you said):
```javascript
handler : this.onXls('exxon'),
scope: this
```
and in function:
```javascript
onXls : function(butt) {
        console.log(butt);
        var grid = this.exceluploadsGrid;

        ...etc
```

What I see in browser console:
```
exxon
TypeError: grid is undefined
...utt);var grid=this.exceluploadsGrid;var params=Kwf.clone(grid.getStore().basePar...
------------------------------------------------------^    
```
Why it doesn't work?

**Comment by nsams** [comment]
You are calling the method while defining the handler.

This is what I ment:

    handler : function() {
        this.onXls('exxon'),
    },
    scope: this

**Comment by Sogl** [comment]
Thx, Niko! 
I can get it now in php by $_REQUEST variable.

How to move this dropdown to right part of panel (after standard xls-button)?
What I can do:
![tbar](https://cloud.githubusercontent.com/assets/7556290/6166290/b1c30ccc-b2fa-11e4-8e83-504b0bc592e1.jpg)

How to create modal dialog with 2 date fields and buttons Continue/Cancel by click on dropdown?

How I can access to grid data like form data:
```
$row = $this->_form->getRow();
$primaryKey = $this->_form->getPrimaryKey();
```
? Now I only get the id.

**Comment by nsams** [comment]
> How to move this dropdown to right part of panel (after standard xls-button)?

Have a look at the ext toolbar docs

> How to create modal dialog with 2 date fields and buttons Continue/Cancel by click on dropdown?

I would not use an Kwf AutoForm for that - instead I would create a plain ExtJS Form (javascript only)

**Comment by Sogl** [comment]
>Have a look at the ext toolbar docs

I found how to align right earlier but this align move right other buttons too =(
I want to align only one dropdown button.

**Comment by nsams** [comment]
Problem is that AutoGrid inserts it's buttons after loading grid meta data.

If you add your custom buttons after the grid is rendered

    grid.on('rendergrid', function() {
         grid.grid.getTopToolbar().add({ ... });
    }, this);

**Comment by Sogl** [comment]
Error:
```
ReferenceError: grid is not defined
...adUrl+'"></iframe>'})}},scope:this})}});grid.on("rendergrid",function(){grid.gri...
----------------------------------------------------^
```

Something wrong with access to my grid I think. I tried to paste `this.exceluploadsGrid` or `exceluploadsGrid` and got errors each time.

I put your code in the end of file. See full code on this link:
https://www.dropbox.com/s/xscy79fthsfzq0e/Exceluploads.js?dl=0

**Comment by nsams** [comment]
sorry, this is totally wrong:

- you don't have a variable named `grid` at all
- you can't access the grid at this position of the file as no objects are created when this code is executed

You have to put this into the initComponent method, and use `Months` instead of `grid` (or `this.exceluploadsGrid`)

**Comment by Sogl** [comment]
Niko, thank you very much! 
It works, but I can't move button to right side... {xtype: tbfill}, or '->' break my code.

**Comment by nsams** [comment]
can you post a screenshot how it looks now?

**Comment by nsams** [comment]
and you can use `->` only once - kwf adds it already probably.

**Comment by Sogl** [comment]
>can you post a screenshot how it looks now?

Left dropdown - old version. Right - new on 'rendergrid'.
![panel](https://cloud.githubusercontent.com/assets/7556290/6919304/44f6f24c-d7f9-11e4-82a1-b5c0469586da.JPG)

>and you can use -> only once - kwf adds it already probably.

All elements has left align by default as I can see. I don't know where put this =)

**Comment by nsams** [comment]
ok.... and with '->'? Do you get an error or what doesn't work?

**Comment by Sogl** [comment]
>ok.... and with '->'?

Xtype and this give me same error.

>Do you get an error or what doesn't work?

Error.
Not so informative as I would like:
```javascript
"NetworkError: 500 Internal Server Error - http://aviashelf/assets/dependencies/Kwf_Assets_Package_Default/Admin/ru/0/js?v=1427788268"
ReferenceError: Ext2 is not defined
Ext2.onReady(function() {
^
```

**Comment by nsams** [comment]
> "NetworkError: 500 Internal Server Error - http://aviashelf/assets/dependencies/Kwf_Assets_Package_Default/Admin/ru/0/js?v=1427788268"

That's the actual error - the javascript file can't be loaded - thus Ext2 is (obviously) not defined.

Open the Url in a new tab and you will see the error, probably some parsing error from uglifyjs. Alternatively you can run a build which also will show that error.

**Comment by Sogl** [comment]
Solved! 

It was necessary to put '->' before first bracket:
```javascript
this.exceluploadsGrid.on('rendergrid', function() {
this.exceluploadsGrid.grid.getTopToolbar().add(
            '->',
            {
                text:'Выгрузки для заказчиков',
                icon: '/assets/silkicons/page_excel.png',
                cls: 'x2-btn-text-icon',
                menu:   [{
                            text:'Выгрузка EXXON',
                            icon: '/assets/silkicons/page_excel.png',
                            cls: 'x2-btn-text-icon',
                            handler: function() {
                                this.onXls('exxon');
                            },
                            scope: this
                        },{
                            text:'Выгрузка SEIC',
                            icon: '/assets/silkicons/page_excel.png',
                            cls: 'x2-btn-text-icon',
                            handler : function() {
                                this.onXls('seic');
                            },
                            scope: this
                        }]
            });
        }, this);
```

>Alternatively you can run a build which also will show that error.

What do you mean?

**Comment by nsams** [comment]
> > Alternatively you can run a build which also will show that error.

> What do you mean?

`php bootstrap.php build`

**Comment by Sogl** [comment]
Ok, I see =)
uglifyjs not so informative, but better than nothing...
