### ISSUE TITLE
Who is online

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#304]
Hi!

How can I implement "who is online" function? I want to see what users now connected to my app.

**Comment by nsams** [comment]
For a backend app that uses sessions you should be able to do that using kwf_sessions table.

**Comment by Sogl** [comment]
>For a backend app that uses sessions you should be able to do that using kwf_sessions table.

This table contains 3 fields: sessionId, expiration and data. But how to show user name from these data?

**Comment by nsams** [comment]
Have a closer look at data - you can unserialize that and get the user id.

With that access the user model and get the user name.

**Comment by Sogl** [comment]
What I done.

Whoisonline.php:
```php
<?php
class Usersmanagement_WhoisonlineController extends Kwf_Controller_Action_Auto_Grid
{
    protected $_modelName = 'Sessions';
    protected $_buttons = array();
    protected $_paging = 100;

    public function indexAction()
    {
        $this->view->ext('Whoisonline');
        $this->view->controllerTitle = trl('Кто онлайн?') . ' &mdash; ';
    }

    protected function _initColumns()
    {
        $this->_columns->add(new Kwf_Grid_Column('sessionId', trl('sessionId')))->setWidth(160);
        $this->_columns->add(new Kwf_Grid_Column('expiration', trl('expiration')))->setWidth(160);
        $this->_columns->add(new Kwf_Grid_Column('data', trl('data')))->setWidth(500);

        $this->_columns->add(new Kwf_Grid_Column('who', trl('who')))->setWidth(160);
    }
}
```

Whoisonline.js:
```javascript
var Whoisonline = Ext2.extend(Ext2.Panel,
{
       initComponent : function(test)
       {
       var grid = new Kwf.Auto.GridPanel({
                                         controllerUrl   : '/usersmanagement/whoisonline',
                                         region          : 'center',
                                         title           : trl('Кто онлайн?')
                                         });

       this.layout = 'border';
       this.items = [grid];
       Checksdocs.superclass.initComponent.call(this);
    }
});
```

Model Sessions.php:
```php
<?php
class Sessions extends Kwf_Model_Db
{
    protected $_table = 'kwf_sessions';
    protected $_rowClass = 'Row_Session';
}
```

Row class Session.php:
```php
<?php
class Row_Session extends Kwf_Model_Db_Row
{
    public function __get($name) {
        if ($name === 'who') {
            $data = (parent::__get('data'));
            $data2 = unserialize($data);

            fb($data);
            fb($data2);

            return 1;
        } else {
            return parent::__get($name);
        }
    }
}
```

Sample data from DB:
```
kwfTimeout|i:1428276539;__KWF|a:1:{s:5:"VALID";a:2:{s:30:"Kwf_Session_Validator_HttpHost";s:18:"HOST";s:32:"Kwf_Session_Validator_RemoteAddr";s:12:"192.168.3.48";}}Zend_Auth|a:1:{s:7:"storage";a:1:{s:6:"userId";i:97;}}sessionToken|a:1:{s:5:"token";s:32:"183604692eb25bae34bcfc06e303f5be";}
```


And now I see error, bacause php can't unserialize this data:
```
exception 'ErrorException' with message 'unserialize(): Error at offset 0 of 303 bytes' in C:\OpenServer\domains\aviashelf\models\Row\Session.php:7
Stack trace:
#0 [internal function]: Kwf_Debug::handleError(8, 'unserialize(): ...', 'C:\\OpenServer\\d...', 7, Array)
#1 C:\OpenServer\domains\aviashelf\models\Row\Session.php(7): unserialize('kwfTimeout|i:14...')
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Data\Table.php(17): Row_Session->__get('who')
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Grid\Column.php(113): Kwf_Data_Table->load(Object(Row_Session), Array)
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Grid.php(387): Kwf_Grid_Column->load(Object(Row_Session), 1, Array)
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Grid->jsonDataAction()
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonDataAction')
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#9 C:\OpenServer\domains\aviashelf\bootstrap.php(20): Kwf_Controller_Front->dispatch()
#10 {main}
```

What's wrong with KWF data string?

**Comment by nsams** [comment]
Hm, that doesn't look like a standard serialized string - I've never noticed that.

You probably can write a custom 'parser'...

**Comment by Sogl** [comment]
In DB:
```
6B776654696D656F75747C693A313432383237363533393B5F5F4B57467C613A313A7B733A353A2256414C4944223B613A323A7B733A33303A224B77665F53657373696F6E5F56616C696461746F725F48747470486F7374223B733A31383A2270756C732E617669617368656C662E636F6D223B733A33323A224B77665F53657373696F6E5F56616C696461746F725F52656D6F746541646472223B733A31323A223139322E3136382E332E3438223B7D7D5A656E645F417574687C613A313A7B733A373A2273746F72616765223B613A313A7B733A363A22757365724964223B693A39373B7D7D73657373696F6E546F6B656E7C613A313A7B733A353A22746F6B656E223B733A33323A223138333630343639326562323562616533346263666330366533303366356265223B7D
```

but I see other string in output:
```
kwfTimeout|i:1428276539;__KWF|a:1:{s:5:"VALID";a:2:{s:30:"Kwf_Session_Validator_HttpHost";s:18:"HOST";s:32:"Kwf_Session_Validator_RemoteAddr";s:12:"192.168.3.48";}}Zend_Auth|a:1:{s:7:"storage";a:1:{s:6:"userId";i:97;}}sessionToken|a:1:{s:5:"token";s:32:"183604692eb25bae34bcfc06e303f5be";}
```

Also if I want to see converted timestamp.
Code:
```
else if ($name === 'expiration') {
            $expiration = (parent::__get('expiration'));

            $exp = new DateTime();
            $exp->setTimestamp($expiration);

            fb($exp);
            fb($exp->format('d.m.Y H:i:s'));

            return $exp->format('d.m.Y H:i:s');
 }
```

I see in table:
```
6
```

Where data converts?

**Comment by nsams** [comment]
> In DB:

That is probably done by phpmyadmin (or whatever tool you use) to show BLOBs.

> Also if I want to see converted timestamp.

Don't do that in the model. Instead convert it when outputting the value. Or create a second 'virtual' column named eg 'expiration_string'.

Problem is that the column type is auto-detected as integer and the value is converted to integer.

**Comment by Sogl** [comment]
>Don't do that in the model. Instead convert it when outputting the value. Or create a second 'virtual' column named eg 'expiration_string'.

Did it in both ways: in JS with setRenderer and with virtual column =)

Why KWF "fogive" to delete old session entries? Sometimes I see old data rows.
Why if I logout session entry not delete?
Where can I change session time?

**Comment by nsams** [comment]
> Why KWF "forgets" to delete old session entries? Sometimes I see old data rows.

that's how php sessions work, from time to time garbage collection starts, but it is not guaranteed to be always correct

> Why if I logout session entry not delete?

the session contents will be cleared, right? then after some time garbage collection deleted the entry.

> Where can I change session time?

I think you can't change that atm.

> Can I "kick" user with deleting his session row? I want him to logout.

That is not possible currently, you would have to add extra code to ensure that

**Comment by Sogl** [comment]
I did it, but.... it not works as I want.

Sometimes I can't see userId:
```
 kwfTimeout|i:1430031307;__KWF|a:1:{s:5:"VALID";a:2:{s:30:"Kwf_Session_Validator_HttpHost";s:18:"HOST";s:32:"Kwf_Session_Validator_RemoteAddr";s:12:"192.168.3.19";}}Zend_Auth|a:1:{s:7:"storage";N;}
```
Why this data not save?

>that's how php sessions work, from time to time garbage collection starts, but it is not guaranteed to be always correct

How to force it or do it manually?
Today 28 of April and I see all sessions with end date 26 and nothing with today date:
![sessions](https://cloud.githubusercontent.com/assets/7556290/7362598/de6b0c7c-edae-11e4-9934-8d9550636ae3.JPG)

>the session contents will be cleared, right? then after some time garbage collection deleted the entry.

No, `sessionId` not cleared =(
Just change timestamp (+ 24 minutes, I checked).

>I think you can't change that atm.

What does "atm" mean?

**Comment by Sogl** [comment]
Some questions about KWF:
1. How can I put virtual columns first? I see error when try to doing this.
2. How to hide/not show whole row by condition of column value?

**Comment by Sogl** [comment]
PHP garbage collector suxx...now I have 62 rows in DB, but only 10 of them has timestamp > current time.

**Comment by nsams** [comment]
.... thinking about that... maybe it's not the best idea to reuse sessions for that.
Instead add some code into bootstrap that stores the data of the last request somewhere (eg per user in kwf_users).

after Kwf_Setup::setUp():

    $u = Kwf_Registry::get('userModel')->getAuthedUser();
    if ($u) {
        $u->last_access = date('Y-m-d H:i:s');
        $u->save();
    }

then you can access the table and count the online users:

    SELECT COUNT(*) FROM kwf_users WHERE last_access > '".date('Y-m-d H:i:s', time()-15*60)."'
