### ISSUE TITLE
Firefox eats memory and CPU with opened Firebug console

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#315]
Hi!

I use latest Firefox (36.0.1) and Firebug (2.0.8) and recently began to notice the browser freezes with opened Firebug console (F12).
Memory 500 mb, CPU 25% - 10-15 seconds the process is not responding. Bug in chrome://firebug/content/lib/trace.js:36
This happened in every page refresh in both server OS: Windows and Linux. If you close FB console - problem disappear.

Non-KWF projects works well.

**Comment by Sogl** [comment]
Huh...now I see freezes without F12 FB console.

Debugger shows me this code part in file Ext.js (line 292):
```javascript
override : function(origclass, overrides){
            if(overrides){
                var p = origclass.prototype;
                for(var method in overrides){
                    p[method] = overrides[method];
                }
                if(Ext2.isIE && overrides.toString != origclass.toString){
                    p.toString = overrides.toString;
                }
            }
        },
```

**Comment by nsams** [comment]
We also have seen this. Must be caused by an Firefox or Firebug update.

I really don't have any idea what causes this?!

**Comment by Sogl** [comment]
Found something:
http://www.sencha.com/forum/showthread.php?286933-Firebug-2.0-breaks-ExtJS
https://bugzilla.mozilla.org/show_bug.cgi?id=998908
https://bugzilla.mozilla.org/show_bug.cgi?id=996456

**Comment by nsams** [comment]
ah, good to know - thanks for your research.

**Comment by Sogl** [comment]
In bugs they say about v. 30 of Firefox.... 31 beta fix issues.
But I see them in last 36 =(

**Comment by Sogl** [comment]
Woohoo!
In the last Firefox 37.0.2 with Furebug 2.0.9 problem is gone away! =)))

**Comment by nsams** [comment]
good to know :D

**Comment by Sogl** [comment]
Last Firebug 2.0.11 in Firefox 38.0.5 freeze KWF tab in the same way and crash plugin-container.exe.

I did downgrade to Firebug 2.0.10 and all works well.
