### ISSUE TITLE
Illuminations plugin for Firebug not compatible with Kwf Ext2

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#317]
Hi!

I found cool pligin for ExtJS dev, but it not working in KWF:
https://addons.mozilla.org/ru/firefox/addon/illuminations-for-developers/

In this page I see that it works correctly:
http://dev.sencha.com/deploy/yui-ext/examples/menu/menus.html

In KWF i see message: "jQuery 1.11.1 was found on this page, but there is nothing to display under 'Widget'."

**Comment by nsams** [comment]
That is probably because we name Ext under Ext2 namespace.

maybe adding window.Ext = window.Ext2 does help?

**Comment by Sogl** [comment]
>maybe adding window.Ext = window.Ext2 does help?

In `config.ini`, right?

Nothing has changed.

**Comment by nsams** [comment]
no, in javascript.

not inside any function, as window.Ext2 is global

**Comment by Sogl** [comment]
Can I add it globally?

**Comment by nsams** [comment]
in any javascript file where you can access window object

I don't know if this works though... was just an idea.

**Comment by Sogl** [comment]
It works if you add `window.Ext = window.Ext2` to every debugging js-file.

**Comment by nsams** [comment]
closing then
