### ISSUE TITLE
Xdebug and Chrome

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#321]
Hi!

Today I tried to setup Xdebug for Sublime Text 3... xdebug open new tab in Chrome with `?XDEBUG_SESSION_START=sublime.xdebug` and nothing loads into grids - "Loading...".

Looks like old error with ExtJS time loop.

**Comment by nsams** [comment]
Sorry, I can't give you support how to set up xdebug.

Check the console for javascript and/or network errors.

**Comment by Sogl** [comment]
Ok, I thought you use this debugger =)

I also created an issue in ST3 xdebug repo:
https://github.com/martomo/SublimeTextXdebug/issues/139
