### ISSUE TITLE
Can't save. User: '94' was not found in the haystack

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#326]
Hi!

Today I can't save my data in form and got an error:
![save](https://cloud.githubusercontent.com/assets/7556290/7265497/29a83726-e8de-11e4-9175-69fb09081a70.JPG)

Somewhere it works (other user) somewhere not.... 

I found problem about ZF2 validator:
http://stackoverflow.com/questions/11231870/zend-form-validation-value-was-not-found-in-the-haystack-error
http://stackoverflow.com/questions/10205624/why-do-i-get-the-error-0-was-not-found-in-the-haystack

How to disable it or fix this error?

**Comment by Sogl** [comment]
How to find the field, which validator reacts?

**Comment by nsams** [comment]
That is a validator from a Field_ComboBox. Try commenting out all but one and try to find the problematic field by trying that on all ComboBoxes.

**Comment by Sogl** [comment]
Fixed, but I have questions...

My table 'employee'.
I found that 94 - userID (related to 'kwf_users').
94 user in 'kwf_users' table was deleted (set 'deleted' field to 1). 
After all ComboBox shows me 'not chosen', but row still exists. Why? In DB i saw value '94' and error after trying to save.

When I chose 'not chosen' and save it - in DB '94' become (NULL) and error gone...

Why the rows are not removed in 'kwf_users'?
How to revert deleted users from web-app?

**Comment by nsams** [comment]
> After all ComboBox shows me 'not chosen', but row still exists. Why? In DB i saw value '94' and error after trying to save.

94 is not in the list of allowed values, but is used as current value. Thus 'not chosen' is selected - but if you save without changing the value the original value (as you didn't change it) will be sent to the server - causing validation to fail.

You need to make sure when a user is deleted that value is also set to null. Or you must disable deleting users that are used somewhere.

> Why the rows are not removed in 'kwf_users'?

To be able to un-delete them.

> How to revert deleted users from web-app?
un-delete by setting deleted to 0. You can do that manually only.

**Comment by Sogl** [comment]
>You need to make sure when a user is deleted that value is also set to null. 

How can I put NULL to reference tables after delete event on kwf_users table? MySQL trigger or from php?

**Comment by nsams** [comment]
> How can I put NULL to reference tables after delete event on kwf_users table? 
> Can't do this by MySQL trigger because rows are not removed.

yes, you can't do that using mysql relations. You could user mysql triggers tough.
Or your add php code that does that:

- create your own user model class (if you don't have one yet)
- configure that in config.ini so it will be used
- override row class
- implement _afterSave where you can add any logic that updates other models

**Comment by Sogl** [comment]
I put this code to user model class or row - nothing happenes:
```
protected function _afterSave(Kwf_Model_Row_Interface $row) {
        fb($row);
        p("ddd");
    }
```

**Comment by nsams** [comment]
I need all the code related to your model

**Comment by Sogl** [comment]
Users.php:
```php
<?php
class Users extends Kwf_User_Model
{
    protected $_rowClass = 'Row_User';
}
```

Row class User.php:
```php
<?php
class Row_User extends Kwf_User_Row
{
    public function __toString()
    {
        $ret = '';
        if ($this->lastname) $ret .= $this->lastname.' ';
        if ($this->firstname) $ret .= $this->firstname;
        if ($this->title) $ret .= ' — '.$this->title;
        $ret = trim($ret);
        if (!$ret) $ret = $this->email;
        return $ret;
    }
}
```

I put my code to both files - no reactions...

**Comment by nsams** [comment]
that looks correct.

Are you using the Users model itself?
(set in config.ini?)

**Comment by Sogl** [comment]
Yes, it set it config.ini.

**Comment by nsams** [comment]
ok.... where do you change the user?

**Comment by Sogl** [comment]
In Kwf_User_Users, extended by my controller.

**Comment by nsams** [comment]
Ah, I think I know what the problem is here. You are not editing the `user.model` directly here, instead this is `user.kwfUserController.model`.

So please, create a second model UserEdit inheriting from `Kwf_User_EditModel` where you put your additional logic.

Then, to actually use it you need to:

- define it in config (`user.kwfUserController.model`)
- set it as proxy model in your User model, eg: `protected $_proxyModel = 'UserEdit';`

**Comment by nsams** [comment]
I think that issue can be closed
