### ISSUE TITLE
Column order in the query

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#329]
Hi!

I tried to sort my combobox refering to 'kwf_users'.
Code:
```
$userModel = Kwf_Model_Abstract::getInstance('Kwf_User_Model');
$userSelect = $userModel->select()->whereEquals('deleted', '0')->order('lastname');

$tab->fields->add(new Kwf_Form_Field_Select('userId', trlKwf('User')))
        ->setValues($userModel)
        ->setSelect($userSelect)
        ->setWidth(400)
        ->setShowNoSelection(true)
        ->setAllowBlank(true);
```

Select in querylog:
```
SELECT `kwf_users`.* FROM `kwf_users` WHERE (kwf_users.deleted = '0') AND (deleted = 0) ORDER BY `kwf_users`.`lastname` ASC
```

It select all fields but put into combobox only 3 by this way:
`title firstname lastname`

But I want:
`lastname firstname` or `lastname firstname - title`

How to do this?

**Comment by nsams** [comment]
you can use `->order()` multiple times

    ->order('lastname')->order('firstname');

you can also use

    ->order(array('lastname', 'firstname'))

the select api is similar to http://framework.zend.com/manual/1.12/en/zend.db.select.html#zend.db.select.building.order

**Comment by Sogl** [comment]
Select is change:
```
SELECT `kwf_users`.* FROM `kwf_users` WHERE (kwf_users.deleted = '0') AND (deleted = 0) ORDER BY `kwf_users`.`lastname` ASC, `kwf_users`.`firstname` ASC
```
but nothing changed in result.

Why select give me all columns but I see only 3?

**Comment by Sogl** [comment]
I don't want to change sort, I want to change order of the columns.
Not `title firstname lastname` but `lastname firstname`.

**Comment by nsams** [comment]
ah, now I understand.

this is implemented in `Kwf_User_Row::__toString`.

Two ways to change that:

1. create your own User Row Class and override `__toString`
2. set the values as array for the combobox

    $values = array(
        1 => 'foo bar'
    )

**Comment by Sogl** [comment]
>this is implemented in Kwf_User_Row::__toString.

where I can find it for this:
```
$userModel = Kwf_Model_Abstract::getInstance('Kwf_User_Model');
```

**Comment by nsams** [comment]
override the row class by:

1. create your own class inheriting Kwf_User_Model
2. instanciate that new model using Kwf_Model_Abstract::getInstance('YourUserModelClassName');
3. in that new class you can specify a protected $_rowClass
4. create new row class inheriting Kwf_User_Row
5. implement your custom logic in the row class

Additionally, since this is the user model add that to config.ini:
user.model = YourUserModelClassName

this makes sure Kwf_Registry::get('userModel') also returns instance of that class (which will be used in kwf)

**Comment by Sogl** [comment]
Thank you, Niko. I did it.

Can I use more than 1 user controller in the same time? For example, in one controller I use users1, in another use users2.

**Comment by nsams** [comment]
A http request is usually dispatched to one, single controller action. You can't have two.

You can however forward to another controller - but question is then what happens to the output of both actions - they somehow have to be merged - which will get messy.

you'll find more about that here:
http://framework.zend.com/manual/1.12/en/zend.controller.html
