### ISSUE TITLE
Big .\uploads folder

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#330]
Hi!

Today uploads folder takes about 4 gigabytes... we use it to put flight pdf scanned files. 
How can I get rid of this folder? 
Maybe put files into DB? But this will significantly increase its size...

This folder adds additional problems for horizontal scaling and gradually eats up disk space on the web server virtual machine.

**Comment by nsams** [comment]
While you could store the binary data in mysql I would really not do that. Look out for another storage solution.

What are your options?

**Comment by Sogl** [comment]
>While you could store the binary data in mysql I would really not do that. Look out for another storage solution.
Why?

>What are your options?
We are in thinking process now =)
External data storage (SSD) with replication (we have 3 branch offices). 
We also need to be able to work with the project without the connection between the branches and synchronize data when a connection.

**Comment by nsams** [comment]
http://stackoverflow.com/questions/561447/store-pictures-as-files-or-in-the-database-for-a-web-app

What you want to do depends on your use case.

re-sync sounds complicated (you can have conflicts!) I would use something already existing optimized for that.

**Comment by Sogl** [comment]
>I would use something already existing optimized for that.
What can you advise? I have no experience of scaling web-applications.

First, can I use external server path as path of `.\uploads`?

**Comment by nsams** [comment]
> I think if we put all files to DB and do master-master mysql replication with all our branch offices - it resolve the problem... i want to believe =)

Yes, if you don't have that many files and the database has enough space for that it's probably the easiest way to go. You should be able to implement that by overriding a few methods in the Uploads Row class. I can give you code examples if you want.

> What can you advise? I have no experience of scaling web-applications.

You could use Amazon S3.

> First, can I use external server path as path of .\uploads?

eg. If you mount that external server using NFS...

**Comment by Sogl** [comment]
>You should be able to implement that by overriding a few methods in the Uploads Row class. I can give you code examples if you want.

Please =)
Storing in DB in special table?

>You could use Amazon S3.

Files and data must be on our servers...

**Comment by nsams** [comment]
1. create a contents row in kwf_uploads table with type BLOB

2. write file contents in `Kwf_Uploads_Row` by overriding `writeFile`:


        public function writeFile($contents, $filename, $extension, $mimeType = null)
        {
            $this->filename = $filename;
            $this->extension = $extension;
            $mimeType = self::detectMimeType($mimeType, $contents);
            $this->mime_type = $mimeType;
            $this->contents = $contents;
            $this->save();
            return $this;
        }



3. read file contents by creating a temporary file in `getFileSource`:

        public function getFileSource()
        {
            $fileSource = parent::getFileSource();
            if (!file_exists($fileSource)) {
                file_put_contents($fileSource, $this->contents);
            }
            return $fileSource;
        }

**Comment by nsams** [comment]
I think we could close that for now

**Comment by Sogl** [comment]
I'll try.
But what about existing files in uploads? I need to write an external script to put them into the BLOB?

**Comment by nsams** [comment]
yep, but that should be not too difficult

**Comment by Sogl** [comment]
Hm... first of all, how to register my new uploads_Row class in KWF? It uses in many parts of my app.

**Comment by nsams** [comment]
1. You create a new Uploads Model (Inheriting the kwf one)
2. you define protected $_rowClass in there
3. you use everywhere your own Uploads model instead of the kwf one

> Also what 'mediaprescale' folder do?

A cache to improve performance for scaling large images. The cache is not cleared on clear-cache
