### ISSUE TITLE
Call external url with existing session and user pass

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#333]
Hi!

How can I call external url with sending $_SESSION variables?
I want to create some external PHP code to use with existing Zend DB connection and other vars.
`.\test\test.php` for example

Another situation.
I want to use Exchange OWA auth from KWF url call. How to get it work described there:
http://blog.degree.no/2011/09/outlook-web-app-2010-auto-login/
This code works great.

I did some changes to panel right menu:
```
this.add({
            cls: 'x2-btn-text-icon',
            icon: '/assets/silkicons/email.png',
            tooltip: trl('E-mail'),
            text: trl('E-mail'),
            handler : function(){
                window.open(
                  'https://exchangeserver/owa',
                  '_blank' // <- This is what makes it open in a new window.
                );
            },
            scope: this
        });
```

But I want to auto-auth user with code in url...also I need to save plain text password somewhere, because DB store it's hash only.

Any ideas?

**Comment by nsams** [comment]
$_SESSION is a standard php feature, you can use that from any file. However you need to use the custom Kwf session handler code.

....is that some kind of Single Sign On? Where you get redirected to an external url which redirects back?

**Comment by Sogl** [comment]
>However you need to use the custom Kwf session handler code.
Where I can read about or fing something useful?

>....is that some kind of Single Sign On? Where you get redirected to an external url which redirects back?
Something like SSO. Url not redirect back, I just need to send values to external url where OWA is located.

**Comment by nsams** [comment]
> > However you need to use the custom Kwf session handler code.
> Where I can read about or fing something useful?

it's implemented in `Kwf_Util_SessionHandler`

> > ....is that some kind of Single Sign On? Where you get redirected to an external url which redirects back?
> Something like SSO. Url not redirect back, I just need to send values to external url where OWA is 

SSO is possible to implement using custom auth methods, for example this implements google oauth login: https://github.com/koala-framework/kwf-google-auth

**Comment by Sogl** [comment]
>SSO is possible to implement using custom auth methods, for example this implements google oauth login: https://github.com/koala-framework/kwf-google-auth

At which point this code is executed? Login into KWF with google?

**Comment by nsams** [comment]
> At which point this code is executed? Login into KWF with google?

You define the auth method in the user model and kwf will present a "login with google" button at the login.

This needs documentation (is on my todo list)

**Comment by Sogl** [comment]
I need to try. How to setup?

**Comment by nsams** [comment]
I wrote some documentation: http://www.koala-framework.org/documentation/kwf_general_features/users/auth_google_oauth_login

**Comment by Sogl** [comment]
Do I need 3.9 version for this module?

**Comment by nsams** [comment]
yes (composer will tell you that)
