### ISSUE TITLE
append querylog

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#335]
Hi!

How to enable? I need to see all queries, but file often overwrites by KWF.

**Comment by Sogl** [comment]
Also not all queries are shown...

**Comment by nsams** [comment]
yes, this file is overwritten for every request.

This is implemented in `Kwf_Db_Profiler`, which is based on Zend_Db_Profiler. You can use your own profiler by setting:

    $db->setProfiler(new MyOwnProfiler());

In your own you can for example implement that the file is not overwritten.

Regarding the not all queries shown... I never experienced that, are you sure that is not caused by overwriting the file?

**Comment by Sogl** [comment]
>You can use your own profiler
Can I use it globally?

>are you sure that is not caused by overwriting the file?
Not sure, but can't see my queries in this file after PHP work.

**Comment by nsams** [comment]
>> You can use your own profiler
> Can I use it globally?

yes - if you add the profiler in bootstrap.php directly after ::setUp()

> > are you sure that is not caused by overwriting the file?
> Not sure, but can't see my queries in this file after PHP work.

often multiple php requests are created for loading images/assets or even just the favicon

**Comment by Sogl** [comment]
>You can use your own profiler by setting

In which folder put this file? controllers?

**Comment by Sogl** [comment]
Sometimes I see not complete queries:
```sql
1 ----------------------
SELECT `kwf_users`.* FROM `kwf_users` WHERE (kwf_users.id = 107) AND (deleted = 0) LIMIT 1
0
Sum: 0
2 ----------------------
SELECT `fli2 ----------------------
SELECT `flightResults`.* FROM `flightResults` WHERE (flightId = '6301') ORDER BY `flightResul3 ----------------------0
Sum: 0.00099992752075195
3 ----------------------
SELECT COUNT(*) c FROM `flightResults` WHERE (flightId = '6301')
0
Sum: 0.00099992752075195
```

**Comment by nsams** [comment]
> >You can use your own profiler by setting
> In which folder put this file? controllers?

I would put it in app, it's not a controller.

> >yes - if you add the profiler in bootstrap.php directly after ::setUp()
> Doesn't work:
> `Undefined variable: db`

Come on, you can't use an undefined variable. Get the db by `Kwf_Registry::get('db')`.

> Sometimes I see not complete queries:

Yes, that can happen if multiple requests happen at the same time (in parallel). Our Profiler isn't capable of that.

**Comment by Sogl** [comment]
Did it.

bootstrap.php:
```php
Kwf_Setup::setUp();

$db = Kwf_Registry::get('db');
$db->setProfiler(new ProfilerEx(true));
```

app\ProfilerEx.php:
```php
<?php
class ProfilerEx extends Kwf_Db_Profiler
{
    public function __construct($enable)
    {
        parent::__construct($enable);

        $writer = new Kwf_Log_Writer_Stream(APP_PATH . '/querylog2', "a");
        $writer->setFormatter(new Zend_Log_Formatter_Simple("%message%\n"));
        $this->_logger = new Zend_Log($writer);
    }
}
```

It not rewrite if I use other (not 'querylog') filename, why?

**Comment by nsams** [comment]
good :D

because you inherit Kwf_Db_Profiler and call the parent constructor - which also creates a logger - in 'w' mode which overwrites the file

**Comment by Sogl** [comment]
I extend KWF profiler and call parent -  KWF profiler. KWF profiler call parent - Zend Profiler. Right?
I overwrite all vars in my class after call parent class... and don't understand why this happened.

**Comment by nsams** [comment]
You call `parent::__construct($enable);` which actually calls `Kwf_Db_Profiler::__construct` where this line gets executed: `new Kwf_Log_Writer_Stream(APP_PATH . '/querylog', 'w');`

And that opens querlog in 'w' mode - which overwrites the file.

Easy workaround: call `Zend_Db_Profiler::__construct($enable)` instead

**Comment by Sogl** [comment]
>Easy workaround: call Zend_Db_Profiler::__construct($enable) instead
Doesn't work with querylog...file rewrites every time.

**Comment by nsams** [comment]
Really?

Something is wired then....

can you post the code somewhere?

**Comment by Sogl** [comment]
Of course.

bootstrap.php:
```php
<?php
chdir(dirname(__FILE__));
$include_path  = get_include_path();




set_include_path($include_path);
require 'vendor/koala-framework/koala-framework/Kwf/Setup.php';
Kwf_Setup::setUp();

$db = Kwf_Registry::get('db');
$db->setProfiler(new ProfilerEx(true));

//Kwf_Session::start();
//d($_SESSION);

Kwf_Setup::dispatchMedia();
//Kwf_Assets_Loader::load();

$front = Kwf_Controller_Front::getInstance();
$response = $front->dispatch();
$response->sendResponse();
```

app\ProfilerEx.php:
```php
<?php
class ProfilerEx extends Kwf_Db_Profiler
{
    public function __construct($enable)
    {
        //parent::__construct($enable);
        Zend_Db_Profiler::__construct($enable);

        $writer = new Kwf_Log_Writer_Stream(APP_PATH . '/querylog', 'a');
        $writer->setFormatter(new Zend_Log_Formatter_Simple("%message%\n"));
        $this->_logger = new Zend_Log($writer);
    }
}
```

**Comment by nsams** [comment]
Ah, I think I know what's happening: you have `debug.querylog` enabled so Kwf_Db_Profiler is also used (by Kwf itself).

Disable querylog and you have the log under your complete control.

You can also add a (temprorary) exception in `Kwf_Db_Profiler` constructor and have a look at the backtrace.

**Comment by Sogl** [comment]
>Ah, I think I know what's happening: you have debug.querylog enabled so Kwf_Db_Profiler is also used (by Kwf itself).

You're right, it works now =)

>You can also add a (temprorary) exception in Kwf_Db_Profiler constructor and have a look at the backtrace.

Can you give an example? I usually watch the values of variables through the FirePHP.

**Comment by nsams** [comment]
> Can you give an example? I usually watch the values of variables through the FirePHP.

Example of throwing an exception? `throw new Exception('foo');`

You'll get a full backtrace and you can track where the call originated from.
