### ISSUE TITLE
SQL queries optimization

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#336]
Hi!

As I can see in querylog, all queries select all rows from database. For example, I need only id, but all 11 columns is selected.

How to specify columns?

**Comment by nsams** [comment]
When using row objects you can't do that. You can however do that when using export:
http://www.koala-framework.org/documentation/kwf_general_features/models/export_import

Usually selecting all columns is not the bottleneck of your queries and reducing that doesn't help much. (Sometimes it is though, but then using export will save additional memory anyway)

**Comment by yacon** [comment]
If you have large amounts of data and your queries are complex (for example with many parent or child selects) it is better to create manual sql queries like so:

    $db = Kwf_Registry::get('db');
    $sql = 'my awesome SELECT';
    $rows = $db->query($sql)->fetchAll();

Watch out for proper quotes. ($db->quote())

**Comment by Sogl** [comment]
>Watch out for proper quotes. ($db->quote())

What do you mean by that?

Usually I use slash `\` to screen sting and data values. Like this:
```sql
'... ownerId = ' . $employee->id . ' AND flightDate <= \'' . $endDateMonth1->format('Y-m-d') . '\' AND ...
```

**Comment by nsams** [comment]
http://framework.zend.com/manual/1.12/de/zend.db.adapter.html#zend.db.adapter.quoting
