### ISSUE TITLE
before save and before delete

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#339]
Hi!

How to get full row in KWF before update values in it? I need DB row, not from form as I do using `_beforeInsert`.

What I do:
1. I create new row in DB and update other tables by `_afterSave` using KWF ORM.
2. I delete/edit this row and before update or delete I need to use my func to re-do my changes in other tables from point 1.
3. I update or create DB row again and do my ORM things that already work.

In general, I need to have a connection with the old record and using it's ID update other tables.
How to do that?

**Comment by Sogl** [comment]
Ok, fount that `_beforeSave` do what I need....but how I can know it's a new line or edit an old?

And what about `_beforeDelete` and `_afterDelete`? This events don't work.

**Comment by nsams** [comment]
Sorry, I don't really get your question :/

`_beforeDelete` and `_afterDelete` both exist and should work! Maybe you can post code where the problem can be seen or reproduced.

**Comment by Sogl** [comment]
My controller:
https://gist.github.com/Sogl/609c12aa76e5a7e1f152

I add `_beforeDelete` and `_afterDelete`(after line 104). Both not working after I delete row by delete button... other code working fine.

**Comment by nsams** [comment]
Ah, ok - I unterstand.

Problem is that you implemented this in the form controller - and the form is not resposible for deleting - that's done by the grid (I guess)

So you can implement that in the AutoGrid controller.

OR: you can implement it in the model (row) directly - so it doesn't matter which controller is actually used.

    class Flightgroups extends Kwf_Model_Db
    {
        protected $_rowClass = 'Flightgroups_Row';
    }

    class Flightgroups_Row extends Kwf_Model_Db_Row
    {
        protected function _beforeDelete()
        {
            parent::_beforeDelete()
            //add your code here, you can access the row using $this->
        }
    }

**Comment by Sogl** [comment]
Ok, thanks. This code works... but how can I specify from which of controllers `_beforeDelete` called? 
Or it works only when I delete row in `Flightgroups` in frontend?

**Comment by nsams** [comment]
the ajax request that does the delete has a specific url and this url gets dispatched to a controller.

And that controller can have a _beforeDelete.

But, it's better in most cases to implement that in Model (+row) so you don't have to care about the actual used controller.

**Comment by Sogl** [comment]
Interesting... if I delete all rows that shows in next tab, clicking on edit shows me:
![delete](https://cloud.githubusercontent.com/assets/7556290/7764665/e176b3fc-0097-11e5-900e-c1efaa6f7ee1.JPG)
Only F5 helps.

Can I programmatically re-draw tab or rows in it?

**Comment by Sogl** [comment]
Also how to get `_cleanData` after delete? 
I need to use same row values, but after delete I see them only in `_cleanData` and this code not working:
```
$this->_cleanData
```

**Comment by nsams** [comment]
> Also how to get _cleanData after delete?

Usually `$this->getCleanValue('flightId')`, but not after delete. Do all operations where you need in _beforeDelete

> Can I programmatically re-draw tab or rows in it?

you can reload the grid in javascript using `grid.reload()`

**Comment by Sogl** [comment]
>Usually $this->getCleanValue('flightId'), but not after delete. Do all operations where you need in _beforeDelete

I tried... but in my case it not working. Before delete row is exists, I'm check it and it still exists, but should not. I need _afterDelete in that case.

>you can reload the grid in javascript using grid.reload()
How to do this in php?

**Comment by nsams** [comment]
>> Usually $this->getCleanValue('flightId'), but not after delete. Do all operations where you need in _beforeDelete

> I tried... but in my case it not working. Before delete row is exists, I'm check it and it still exists, but should not. I need _afterDelete in that case.

yes, before is before the delete, but that is the only place where you still can access the data. What are you trying to do?


>> you can reload the grid in javascript using grid.reload()

> How to do this in php?

You can't trigger a reload from php

**Comment by Sogl** [comment]
>What are you trying to do?

1. I delete row from table 1st (1st tab in frontend).
2. _beforeDelete I use to delete data in 2nd table (relative to 1st table deleting row). On this step I also need to reload my data view (2nd tab).
3. _afterDelete
This step I want to use func to generate/calculate data to 3rd table passing data from 1st deleting row. Function checks how much rows relative in 2nd to 1st.

In general, I want to revert my changes in tables after delete.

That's why I need _beforeDelete data.

**Comment by Sogl** [comment]
>Usually $this->getCleanValue('flightId'), but not after delete. 

If after delete:
```
exception 'Kwf_Exception' with message 'Invalid column 'getCleanValue' for model 'Flightgroups'' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Row\Abstract.php:167
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db\Row.php(51): Kwf_Model_Row_Abstract->__get('getCleanValue')
#1 C:\OpenServer\domains\aviashelf\models\Row\Flightgroup.php(41): Kwf_Model_Db_Row->__get('getCleanValue')
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Model\Db\Row.php(122): Row_Flightgroup->_afterDelete()
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Grid.php(599): Kwf_Model_Db_Row->delete()
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Auto\Grid.php(590): Kwf_Controller_Action_Auto_Grid->_deleteRow(Object(Row_Flightgroup))
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf_Controller_Action_Auto_Grid->jsonDeleteAction()
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('jsonDeleteActio...')
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#9 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
#10 {main}
```

But I see this values in $this... need to get it.

**Comment by nsams** [comment]
use a method call, you seem to be using `$this->getCleanValue` without `()` or so.

And, you can't use afterDelete, use beforeDelete instead.

**Comment by Sogl** [comment]
>And, you can't use afterDelete, use beforeDelete instead.

How I can pass value (deleted row) from beforeDelete to afterDelete?

**Comment by nsams** [comment]
>> And, you can't use afterDelete, use beforeDelete instead.

> How I can pass value (deleted row) from beforeDelete to afterDelete?

you can't pass something, you could probably remember values in the row or somewhere else... but why not simply use beforeDelete?

**Comment by Sogl** [comment]
I use function to update related table rows and it checks: is row exists or deleted.
On _beforeDelete row still exists - wrong result, but afterDelete I can't get deleted value (ID, for example) :D

**Comment by nsams** [comment]
why not pass the id of the row that will get deleted into that function?

**Comment by Sogl** [comment]
Not a good solution for me, because:
1. +1 function parameter that I need only for this situation
2. row still exists (need to exclude ID in sql query)

**Comment by Sogl** [comment]
Did it with +1 function parameter.

How I can initialize grid redraw/reload after row delete ?

**Comment by nsams** [comment]
You can not trigger/call/do something on the client side javascript on the server side in php. Somehow something must be passed from the server to the client if you want to do that.

But in this case you start the delete from the client side anyway (the code that executes the ajax request that deletes data) and can add the reload there.

Is that delete code you own custom button handler?

**Comment by Sogl** [comment]
>Is that delete code you own custom button handler?

It's standard delete button on the grid. I delete one row and with php delete some rows in DB (other tab). After deleting I want ro reload this tab.

**Comment by nsams** [comment]
The standard button does ask for confirmation (https://github.com/koala-framework/koala-framework/blob/3.8/Kwf_js/Auto/GridPanel.js#L842) and reloads after deleting (https://github.com/koala-framework/koala-framework/blob/3.8/Kwf_js/Auto/GridPanel.js#L830)

If you want to reload other tabs you can do that by listening to the 'deleterow' event.

**Comment by Sogl** [comment]
>The standard button does ask for confirmation (https://github.com/koala-framework/koala-framework/blob/3.8/Kwf_js/Auto/GridPanel.js#L842) 

Yes, but I want to add one more confirm message because sometimes users delete rows with important data (referenced with many rows of the other table).

>If you want to reload other tabs you can do that by listening to the 'deleterow' event.

Can you give an example, please?

Also how to check if `beforeSave` row equals to `afterSave` row? For example, you just save form without changing values in it.
