### ISSUE TITLE
Autosize edit forms

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#340]
Hi!

I have this code:
```
$this->_editDialog = array(
                                           'controllerUrl' => '/works/employeeworksentry',
                                           'width' => 350,
                                           'height' => 600,
                                           'type' => 'WindowFormEx'
                                       );
```

But if I want to change some elements I also need to calibrate form width and height. 
If I disable this parametres I see this:
![editdialog](https://cloud.githubusercontent.com/assets/7556290/7627355/f294af7a-fa59-11e4-8ee7-324280b57e3e.JPG)

Height is normal, but widht... 
Need a fix?

**Comment by Sogl** [comment]
Fount that width of most elements is 5000px =)

**Comment by nsams** [comment]
You can define only a width, height is calculated automatically.

(with should too, but that doesn't work correctly in a tab panel)

**Comment by nsams** [comment]
please re-open if that doesn't help

**Comment by Sogl** [comment]
Found a bug.

1. Form with auto height calculation and 2 tabs:
![screenshot_1](https://cloud.githubusercontent.com/assets/7556290/8321142/a6f9dce8-1a66-11e5-9948-04c2ba7ff7b3.jpg)

2. Click on second tab - height not re-calculate (gray space at the bottom):
![screenshot_2](https://cloud.githubusercontent.com/assets/7556290/8321157/cb67fc90-1a66-11e5-8fb5-b7c6385fd4aa.jpg)

3. If you stay in 2nd tab and than close and reopen form - 1st tab height still equal to 2nd:
![screenshot_3](https://cloud.githubusercontent.com/assets/7556290/8321203/4203d63a-1a67-11e5-8d1e-877b54f0115b.jpg)

4. But the second is OK =)) 
![screenshot_4](https://cloud.githubusercontent.com/assets/7556290/8321212/58459c30-1a67-11e5-9fb9-5b6a02e7f1a4.jpg)

Finally I still use width/height define in all project.

**Comment by nsams** [comment]
Auto height is not supported when using tabs.
