### ISSUE TITLE
Grouping order

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#341]
Hi!

How to change it? I already have defaultOrder field and also need to order my groups.

**Comment by Sogl** [comment]
Can I group with virtual field without showing it in table?

**Comment by nsams** [comment]
Sorry, I don't understand your question...

please post some code.

**Comment by Sogl** [comment]
1st situation.

I use default order field with ASC:
```
protected $_defaultOrder = array('field' => 'workDate', 'direction' => 'ASC');
```
and grouping:
```
protected $_grouping = array('groupField' => 'employeeName');
```

But how to enable order in groups?
eg something like:
```
protected $_defaultOrder = array('field' => 'workDate', 'direction' => 'ASC');
protected $_grouping = array('groupField' => 'employeeName', 'direction' => 'DESC');
```

2nd situation.

Virtual field in form:
```
$this->_columns->add(new Kwf_Grid_Column('workMonthYear', trlKwf('Month')))->setWidth(80);
```
Row class:
```
if ($name === 'workMonthYear') {
            $workDate = new DateTime(parent::__get('workDate'));
            return $workDate->format('m.Y');
}
```
I use it only for grouping:
```
$this->_grouping = array('groupField' => 'workMonthYear');
```

But how to not showing this field in table? I don't need it.

**Comment by nsams** [comment]
> 1st situation.

Good question. As far as I know grouping only works without paging - which means sorting is performed in on client side in javascript by the ext store.

Not much more I can help you with at the moment i fear...

> 2nd situation.

don't give that column a title and it won't be shown in the grid - exist in the store and records though.

**Comment by Sogl** [comment]
>don't give that column a title and it won't be shown in the grid - exist in the store and records though.

If I change to without column title:
```
$this->_columns->add(new Kwf_Grid_Column('workMonthYear'))->setWidth(80);
```

It shows error:
```
TypeError: cfg is undefined
...id;var cfg=this.cm.config[colIndex];var groupRenderer=cfg.groupRenderer||cfg.ren...
```

**Comment by nsams** [comment]
the column needs a name: `new Kwf_Grid_Column('workMonthYear', 'Date')`

**Comment by Sogl** [comment]
But if I put a name - it shows in grid. I need not showing this column, grooping only.

**Comment by nsams** [comment]
If you don't need to show the column you also don't need a width. 

Try removing the setWidth call.

**Comment by Sogl** [comment]
It uses width by default if I not set it.
