### ISSUE TITLE
update selected rows

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#343]
Hi!

For example, I select row(s) by that:
```
$flightPlanModel = Kwf_Model_Abstract::getInstance('Flightplans');
$flightPlanSelect = $flightPlanModel->select()->whereEquals('id', $planId);
$flightPlan = $flightPlanModel->getRow($flightPlanSelect);
```

How to update `$flightPlan` rows?

**Comment by nsams** [comment]
like that?

    $flightPlan->foo = 1;
    $flightPlan->save()

**Comment by Sogl** [comment]
Yes.

Some of this answers confused me:
http://stackoverflow.com/questions/4097234/how-update-a-database-table-record-in-zend

Also the same code in Zend docs:
$table->update($data, $where);

**Comment by nsams** [comment]
That is Zend_Db_Table.

Kwf_Model_Db is not a Zend_Db_Table (tough is uses it internally and it tries so provide a similar api)

There is also an updateRows method:
`$flightPlanModel->updateRows(array('foo'=>1), $flightPlanSelect)`

**Comment by nsams** [comment]
see also that: http://www.koala-framework.org/documentation/kwf_general_features/models/basic_usage
