### ISSUE TITLE
Document trl for 3.9 on koala-framework.org

### ISSUE THREAD

**Issue by nsams** [koala-framework/koala-framework#347]
Add/Update documentation for 3.9 trl related changes

- how to convert trl.xml to po
- how to parse for new strings
- how to work with multiple packages
- how to translate
- how to integrate with lingohub (upload / download)

**Comment by Ben-Ho** [comment]
Is done, please check 
* http://www.koala-framework.org/documentation/kwf_general_features/translation/localisation_3_9_1
* http://www.koala-framework.org/documentation/kwf_general_features/translation/parsing_3_9
* http://www.koala-framework.org/documentation/kwf_general_features/translation/update_to_3_9

for feedback :-)

**Comment by Ben-Ho** [comment]
Improved :-)
