### ISSUE TITLE
3.9: Duplicate entry in trl-files

### ISSUE THREAD

**Issue by nsams** [koala-framework/koala-framework#350]
`php bootstrap.php build` shows this warning but does not cause any problems (I hope)

    c:\OpenServer\domains\aviashelf>php bootstrap.php build
    [ 1/3] building trl......
    Duplicate entry in trl-files: - => ╨Т╨╛╨╖╨╜╨╕╨║╨╗╨░ ╨╛╤И╨╕╨▒╨║╨░ ╨┐╤А╨╕ ╨╛╤В╨┐╤А╨░╨▓╨║╨╡ ╤Д╨╛╤А╨╝╤Л. ╨Я╨╛╨╢╨
    ░╨╗╤Г╨╣╤Б╤В╨░, ╨┐╨╛╨┐╤А╨╛╨▒╤Г╨╣╤В╨╡ ╨┐╨╛╨╖╨╢╨╡.

    Duplicate entry in trl-files: - => '%value%' ╤П╨▓╨╗╤П╨╡╤В╤Б╤П IP-╨░╨┤╤А╨╡╤Б╨╛╨╝, ╨╜╨╛ IP-╨░╨┤╤А╨╡╤Б╨░ ╨╜╨╡ ╨
    ┤╨╛╨┐╤Г╤Б╨║╨░╤О╤В╤Б╤П

**Comment by Ben-Ho** [comment]
Ok, i checked it...
The source of this problem also has effect on matching id to translation.
Note: there is a problem with lingohub and also a problem with how we work with poparser. (there is also a problem in po-parser too)
I'll fix it :-) (but it will take some time...)

**Comment by nsams** [comment]
Is this solved?

**Comment by Ben-Ho** [comment]
Is now solved.
