### ISSUE TITLE
3.9 Trl Parsing js file failed

### ISSUE THREAD

**Issue by nsams** [koala-framework/koala-framework#351]
compiling assets...
    35% [#######--------------] kwf/Kwf_js/Form/File.js                           exception 'Kwf_Exception' wit
    h message 'Parsing js file failed: C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\no
    de_modules\esprima\esprima.js:3718
                throw e;
                    ^
    Error: Line 1: Unexpected end of input
        at throwError (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\espri
    ma\esprima.js:1831:21)
        at throwUnexpected (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\
    esprima\esprima.js:1863:13)
        at expect (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\esprima\e
    sprima.js:1898:13)
        at parseArguments (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_modules\e
    sprima\esprima.js:2217:17)
        at parseLeftHandSideExpressionAllowCall (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-fr
    amework\node_modules\esprima\esprima.js:2283:24)
        at parsePostfixExpression (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_m
    odules\esprima\esprima.js:2325:16)
        at parseUnaryExpression (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_mod
    ules\esprima\esprima.js:2384:20)
        at parseBinaryExpression (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\node_mo
    dules\esprima\esprima.js:2473:16)
        at parseConditionalExpression (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\no
    de_modules\esprima\esprima.js:2533:16)
        at parseAssignmentExpression (C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\nod
    e_modules\esprima\esprima.js:2559:23)
    ' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Trl\Parser\JsParser.php:10
    Stack trace:
    #0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Assets\Dependency\File\Js.php(
    68): Kwf_Trl_Parser_JsParser::parseContent('Kwf.Form.File=E...')
    #1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Assets.php(16
    6): Kwf_Assets_Dependency_File_Js->warmupCaches()
    #2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build\Types\Abstract.php(
    15): Kwf_Util_Build_Types_Assets->_build(Array)
    #3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Util\Build.php(97): Kwf_Util_B
    uild_Types_Abstract->build(Array)
    #4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action\Cli\BuildCon
    troller.php(35): Kwf_Util_Build->build(Array)
    #5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(33): Kwf
    _Controller_Action_Cli_BuildController->indexAction()
    #6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\
    Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
    #7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(9
    54): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller
    _Response_Http))
    #8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(136): Zen
    d_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
    #9 C:\OpenServer\domains\aviashelf\bootstrap.php(22): Kwf_Controller_Front->dispatch()
    #10 {main} [ERROR] (7665ms)

**Comment by Ben-Ho** [comment]
The problem is in your old kwf folder. This folder is not needed anymore.
There are probably js parsing problems in older kwf versions.
Just delete your kwf folder and the problem should be solved :-)
Am 01.06.2015 10:38 schrieb "Niko Sams" <notifications@github.com>:

**Comment by nsams** [comment]
Old kwf folder? I don't think that is the problem. Even if it would exist it would not be accessed.

**Comment by Sogl** [comment]
>Just delete your kwf folder and the problem should be solved :-)

Please, tell full folder path. I don't understand what 'kwf' you mean.

**Comment by nsams** [comment]
@Sogl ignore that comment, @Ben-Ho is already working on a solution for this problem.
