### ISSUE TITLE
custom query in _getWhere

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#361]
Hi!

I want to create custom query like this:
```sql
SELECT `employee`.* FROM `employee` WHERE ((groupType = 1) AND (subCompanyName <> 'Нет')) OR (subCompanyName = 'ВЕГА')
```

My code:
```php
protected function _getWhere()
    {
        $ret = parent::_getWhere();

        $ret['groupType = ?'] = 1;
        $ret['subCompanyName <> ?'] = 'Нет';

        return $ret;
    }
```

How to put brackets and OR construction in it?

Also if I want to use multiply conditions by one field:
```php
$ret['subCompanyName <> ?'] = 'foo';
$ret['subCompanyName <> ?'] = 'bar';
```

then I see only last condition query:
```sql
SELECT `employee`.* FROM `employee` WHERE (subCompanyName <> 'bar')
```

How to use both of them?

**Comment by nsams** [comment]
You can use expressions:

    protected function _getSelect()
    {
        $ret = parent::_getSelect();
        $ret->where(new Kwf_Model_Select_Expr_Or(array(
            new Kwf_Model_Select_Expr_And(array(
                new Kwf_Model_Select_Expr_Equals('groupType', 1),
                new Kwf_Model_Select_Expr_NotEquals('subCompanyName', 'Нет'),
            ),
            new Kwf_Model_Select_Expr_Equals('subCompanyName', 'ВЕГА')
        )));
        return $ret;
    }

see http://www.koala-framework.org/documentation/kwf_general_features/models/expressions

**Comment by Sogl** [comment]
Thanks! 
I didn't know about `_getSelect()` func.
