### ISSUE TITLE
How to get whole data from returned Row

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#375]
Hi!

I'm trying to get full _data from returned array, something like:
```php
$sets = $setsModel->getRows($setsSelect);

$m = array();
foreach ($sets as $set) {
    $m[] = $set->getData();  <---- what the name of this method?
}
```

What I mean:
![screenshot_11](https://cloud.githubusercontent.com/assets/7556290/8490760/ac769424-2171-11e5-89ab-282802881bcd.jpg)

Finally I want to get clean array values, without Kwf_Db_Table_Rows or something =)

**Comment by nsams** [comment]
`->toArray()`
