### ISSUE TITLE
How to pre-calculate date for DateField on form

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#377]
Hi!

Situation (1 FieldSelect and 2 DateFields):
![screenshot_15](https://cloud.githubusercontent.com/assets/7556290/8539253/8c7bae4a-24bc-11e5-9174-4caf0664b30a.jpg)
I want to pre-calculate end date depending on the drop down list and start date. 

For example: 
1. If I choose '3' from dropdown and start date is 07.07.2015:
![screenshot_16](https://cloud.githubusercontent.com/assets/7556290/8539328/58e79bb0-24bd-11e5-9772-e9fdb7f05146.jpg)
2. Then end date value becomes 07.08.2015 (+1 month, depending on DB field of '3' value):
![screenshot_17](https://cloud.githubusercontent.com/assets/7556290/8539351/afd52a3c-24bd-11e5-9df5-867e3912ce8c.jpg)
3. I can change end date if needed.

How to implement it?

**Comment by nsams** [comment]
Using custom javascript that listens to the change event on the combobox and sets the date dynamically. That is pure extjs.

The only kwf dependent thing is that you can't access the fields as they are created by the meta data received from the server. So you need:
`formPanel.on('renderform', function() {
    formPanel.findField(...)
});`

(That would be a good question to post on stackoverflow imho)

**Comment by Sogl** [comment]
>Using custom javascript that listens to the change event on the combobox and sets the date dynamically. That is pure extjs.

But how to select value from DB row in this case? Month value stored in DB and depends with combobox.

**Comment by nsams** [comment]
I see two options:

1. When your combobox uses a remote store you can add addtional values for every row and access that on change

2. You can start an ajax request on change which feteches the required information from the server

**Comment by Sogl** [comment]
@nsams 
Did it in a second way:
https://stackoverflow.com/a/36146830/4827198

But I want to try with your 1st method to exclude additional queries to the database.
So.. how to extend KWF remote store to put +1 additional value?

I found something, but it not clear with KWF:
https://www.sencha.com/forum/showthread.php?229536

**Comment by Sogl** [comment]
@nsams Please tell me how to implement this thing:
>When your combobox uses a remote store you can add addtional values for every row and access that on change

**Comment by nsams** [comment]
> @nsams Please tell me how to implement this thing:

>> When your combobox uses a remote store you can add addtional values for every row and access that on change

- create a AutoGrid controller for values in combobox (+ the required additional column)
- use that controller as remote store by `setValues('url-to-controller/json-data')`
- access the store in javascript by `combobox.store`
- on change get the record using `store.getById` and read the additional field
