### ISSUE TITLE
afterDelete for Kwf_Form_Field_File (delete row and file from disk)

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#405]
Hi!

I use Kwf_Form_Field_File for my forms:
![screenshot_21](https://cloud.githubusercontent.com/assets/7556290/9651294/e40a22dc-5251-11e5-994c-263a0cc265b3.jpg)

Model code:
```
'Picture' => array(
             'column'           => 'picture_id',
             'refModelClass'     => 'Kwf_Uploads_Model'
        )
```

Controller code:
```
$tab->fields->add(new Kwf_Form_Field_File('Picture', trlKwf('File')))
        ->setShowPreview(true)
        ->setAllowOnlyImages(false);
```

But If I click on `Delete file` button, than only `picture_id` becomes 'NULL', but row not delete from `kwf_uploads` table and file still on `.\uploads` folder.

How to fix this?

Also if I add file, it appears in the folder BEFORE I save the form... and if I click on `Cancel`, than file becomes empty on form, but already in the disk.

All of this creates a lot of unuseful files...

**Comment by fraxachun** [comment]
Hello Artyom,

this behaviour is intended and there is currently no way to get around of this.

However, I can think of two solutions, both are not easy to implement.

You can either overwrite Kwf_Form_Field_File and Kwf_js/Form/File.js and add actions to delete the uploads. The other possibility is to create a CLI-Controller which tries to find out all uploads which are not used anymore and delete them.

We currently don't have plans to support either solution. I suggest to leave it like it is and live with some amount of "wasted" storage space.

**Comment by Sogl** [comment]
>The other possibility is to create a CLI-Controller which tries to find out all uploads which are not used anymore and delete them.

I prefer this way because I know PHP much better =)
Just created a workaround with CLI, maybe it helps someone:
https://gist.github.com/Sogl/50bd8a60162c18c33204

But my `echo` commands shows error:
```
exception 'Zend_Controller_Response_Exception' with message 'Cannot send headers; headers already sent in /var/www/puls/controllers/Cli/CleanfilesControllerController.php, line 10' in /var/www/puls/vendor/koala-framework/zendframework1/l
Stack trace:
#0 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Response/Abstract.php(115): Zend_Controller_Response_Abstract->canSendHeaders(true)
#1 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action/Helper/ViewRenderer.php(41): Zend_Controller_Response_Abstract->setHeader('Content-Type', 'text/html; char...')
#2 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(277): Kwf_Controller_Action_Helper_ViewRenderer->postDispatch()
#3 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Action.php(46): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#4 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#5 /var/www/puls/vendor/koala-framework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#6 /var/www/puls/vendor/koala-framework/koala-framework/Kwf/Controller/Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Cli), Object(Kwf_Controller_Response_Http))
#7 /var/www/puls/bootstrap.php(20): Kwf_Controller_Front->dispatch()
#8 {main}
```

My script works, but how to fix this error?

Some other questions:
1. How to limit the upload size of the file for this component? 5MB, for example.
2. How to automatically compress uploaded pdf before put it to server's disk? I think I can do it in php, but WHERE to put my code? =)

**Comment by nsams** [comment]
> My script works, but how to fix this error?

two possibilities to fix this:

- add `$this->_helper->viewRenderer->setNoRender(true);`
- simply `exit;` once your code is finished


> 1. How to limit the upload size of the file for this component? 5MB, for example.

you can change that in php.ini: http://stackoverflow.com/questions/2184513/php-change-the-maximum-upload-file-size

you might be able to set that in .htaccess

> 2. How to automatically compress uploaded pdf before put it to server's disk? I think I can do it in php, but WHERE to put my code? =)

You can't do that as you can't override the upload controller easily. I would create a cronjob that does that...

**Comment by Sogl** [comment]
>add `$this->_helper->viewRenderer->setNoRender(true);`

Thx, it fixed this error.

>you can change that in php.ini:

And user will see php exception?

**Comment by nsams** [comment]
>> you can change that in php.ini:

> And user will see php exception?

No, php doesn't even start in this case. Give it a try and see what's happening...

**Comment by Sogl** [comment]
@nsams After updating to 3.9 my script doesn't work.

1.. In 3.8 all files was in one `uploads` folder, in 3.9 all files separate into different folders:

![image](https://cloud.githubusercontent.com/assets/7556290/18461076/2966610e-79c2-11e6-9b9d-232eefcc855f.png)
How to get full filepath from DB?

2.. How to get filename from any of this string?

![image](https://cloud.githubusercontent.com/assets/7556290/18461271/c6ee8cd4-79c3-11e6-8012-d0fad13c2388.png)

**Comment by nsams** [comment]
yes, that changed

always use `$uploadsRow->getFileSource()`, don't generate paths manually

**Comment by Sogl** [comment]
>always use $uploadsRow->getFileSource(), don't generate paths manually

But I use `$db = Kwf_Registry::get('db');` and direct query that you can see here:
https://gist.github.com/Sogl/50bd8a60162c18c33204

How to use `getFileSource()` function with it?

**Comment by Sogl** [comment]
Ok, I changed my gist with adding `getFileSource()` function. Works now with 3.9.

**Comment by nsams** [comment]
I would use `Kwf_Model_Abstract::getInstance('Kwf_Uploads_Model')->getRow($uploadId)->getFileSource();`
