### ISSUE TITLE
Using external php-file

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#408]
Hi!

I want to use PHP script with SMPP class that not presented in composer.... what is the best way to include it in KWF?

**Comment by nsams** [comment]
- You can create your own composer package (hosted on github, added to packagist.org)
- or you can simply copy into you application, eg in the app/ foder

**Comment by Sogl** [comment]
>or you can simply copy into you application, eg in the app/ foder

Ok, copied into `app` folder... but can't use my class because of error:
```
Fatal error: Class 'smpp' not found in C:\OpenServer\domains\aviashelf\controllers\Cli\CleanfilesControllerController.php on line 9
exception 'ErrorException' with message 'Class 'smpp' not found' in C:\OpenServer\domains\aviashelf\controllers\Cli\CleanfilesControllerController.php:9
Stack trace:
#0 [internal function]: Kwf_Setup::shutDown()
#1 {main}
```

**Comment by nsams** [comment]
what class name do you use?

**Comment by Sogl** [comment]
`smpp`

**Comment by nsams** [comment]
what's the file name? `smpp.php` with that exact casing?

**Comment by Sogl** [comment]
>what's the file name? smpp.php with that exact casing?

My mistake. Filename was `smpp.class.php`. Error is gone after rename.
