### ISSUE TITLE
Load custom lines from config.local.ini to CLI controller

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#414]
Hi!

I'm trying to add some SMPP configuration lines to `config.local.ini` file. Example:
```
sms.smpp.server = <smpp server dns name>
```

But if I try to load this value to my CLI controller:
```php
$server = Kwf_Config::getValue('sms.smpp.server');
var_dump($server);
```

Then I see `NULL` output.
What I'm doing wrong?

**Comment by nsams** [comment]
did you clear caches?

**Comment by Sogl** [comment]
>did you clear caches?

Works now. I forgot about it.

I can use all my own parameter strings in such way?

**Comment by nsams** [comment]
yes, you can add anything you want to config.ini
