### ISSUE TITLE
Using smtp mail and templates

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#420]
Hi!
I have some questions of using mail templates and other:

1. I load html template `*.html.tpl` by this line:

    ```
    $mail = new Kwf_Mail_Template('NewFlightTaskTemplate');
    ```

    How to load `txt.tpl` template?

2. I have two lines in my configuration:
    ```
    email.from.address = puls@aviashelf.com
    email.from.name = Пульс
    ```
    Also I use this string in controller (to override config default):
    ```
    $mail->setFrom('puls@aviashelf.com', 'Авиашельф Пульс');
    ```
    But what I see in my gmail account:
    ![image](https://cloud.githubusercontent.com/assets/7556290/10532303/2abac3c4-7400-11e5-91f2-071c9156f262.png)

    Why name not showing?

3. I use inliner for css and mail template in HTML:

    All  generated code I put into `*html.tpl`. Looks fine, but problem with images.
    I put images here: `C:\OpenServer\domains\aviashelf\views\mails`
    Screen:
    ![image](https://cloud.githubusercontent.com/assets/7556290/10532517/93a0fe74-7402-11e5-9f6e-1f5d8f8ca222.png)

    But images not shown. 

    Example from `tpl`:
    `<img width="24" height="24" src="images/socicons/github.png">`

    What I see in my mail:
    ![image](https://cloud.githubusercontent.com/assets/7556290/10532586/56aed4f4-7403-11e5-8dab-dbd085efde93.png)

    Whats wrong with my path?

I looked here before put this issue:
http://www.koala-framework.org/documentation/kwf_general_features/mails/kwf_mail_template
http://www.koala-framework.org/documentation/kwf_general_features/mails/config
http://www.koala-framework.org/documentation/kwf_general_features/mails/styling
https://groups.google.com/forum/#!topic/koala-framework-dev/3FJSTAqd9HY

**Comment by nsams** [comment]
> I load html template *.html.tpl by this line:
> $mail = new Kwf_Mail_Template('NewFlightTaskTemplate');
> How to load txt.tpl template?

Those get automatically loaded. The Mail you sent contains HTML plus Text. Depending on your mail client you will see html, text or have an option to switch between text and html.


> I have two lines in my configuration:

Strange, that should work. Probably an Charset issue?

I would test with plain Zend_Mail


> I use inliner for css and mail template in HTML:

use `$this->image('/assets/web/images/socicons/github.png');`


oh, and it's probably easier to create an individual issue for every question you have...

**Comment by Sogl** [comment]
>use $this->image('/assets/web/images/socicons/github.png');

I put my image into: `C:\OpenServer\domains\aviashelf\images`
My line now: `<img src="$this->image('/assets/web/images/heli.png');" width="90" height="43">`

And it not working =(

**Comment by Sogl** [comment]
Works it this way: `<img src="/assets/web/images/heli.png" width="90" height="43">`

**Comment by nsams** [comment]
`$this->image('` outputs the whole <img tag, not just the src
