### ISSUE TITLE
MultiFields for manual processing

### ISSUE THREAD

**Issue by daHaimi** [koala-framework/koala-framework#444]
I need to use the Multifields component to process the Data manually later. Is there any way to disable the usage of DB-References or do I have to build my own component for that?

**Comment by fraxachun** [comment]
Kwf_Form_Field_MultiFields requires the main model to have set a reference to the multifields-model and vice versa. However, you could create a Kwf_Model_FnF (or Kwf_Model_FieldRows) which does not depend on a db-table. That way you can process the data in afterSave. See Kwf_Form_MultiFields_Test how to setup.

**Comment by daHaimi** [comment]
Hallo,

danke, das hat wunderbar funktioniert!

Viele Grüße,
Mathias

Am 30.11.2015 um 12:17 schrieb Franz Unger:
