### ISSUE TITLE
Unable to add Button to custom Form

### ISSUE THREAD

**Issue by daHaimi** [koala-framework/koala-framework#445]
I am trying to add a toolbar Button to a Form. According to the documentation, extensions should be done very easily by extending the autoForm. I tried the following:

```javascript
H3S.FormPanel = Ext2.extend(Kwf.Auto.FormPanel,
{
    initComponent: function() {
        this.actions.calculateCost = new Ext2.Action({
              ...
        });
        Kwf.Auto.FormPanel.superclass.initComponent.call(this);
    }
});
Ext2.reg('h3s.rekform', H3S.FormPanel);
```
I found out, that the instantiated Form had only the default actions, even if I add the action to the config option at instantiation time or when I add the action after instatiation.

Is there a way to add buttons to a form?

**Comment by fraxachun** [comment]
You need to add the action to the _buttons property in you form:

class XXX_Controller extends Kwf_Controller_Action_Auto_Form
{
    protected $_buttons = array('save', 'add', 'calculateCost');
    ....
}

**Comment by daHaimi** [comment]
When I do so, i get the error: 

*Uncaught TypeError: Cannot read property 'isFormField' of undefined*

In assets/ext2/src/widgets/Toolbar.js:93:
     if(el.isFormField){ // some kind of form field

**Comment by nsams** [comment]
Start up your javascript debugger and have a look at the backtrace and check why the action added to the toolbar is undefined.

If you put your code somewhere where we can access it we'll have a look...

**Comment by daHaimi** [comment]
Nailed it!

The problem is in the Code of my first post. The Javascript "inheritance" is the Problem. I copy/pasted the Code from the Kwf.Auto.FormPanel, but I have to use
```javascript
H3S.FormPanel.superclass.initComponent.call(this);
```

**Comment by nsams** [comment]
:+1:

**Comment by Sogl** [comment]
@fraxachun How to add my own buttons/dropdown button menu to this array in PHP:
```
protected $_buttons = array('save', 'add');
```

I need to change buttons depending on user role.

**Comment by nsams** [comment]
public function preDispatch()
    {
        if (Kwf_Registry::get('userModel')->getAuthedUserRole() == 'admin') {
            $this->_buttons[] = 'delete';
        }
        parent::preDispatch();
    }

**Comment by Sogl** [comment]
@nsams What the `preDispatch()` function does ?

My js code:
```javascript
this.exceluploadsGrid.on('rendergrid', function() {
        this.exceluploadsGrid.grid.getTopToolbar().add(
            '->',
            {
                text:'Unload',
                icon: '/assets/silkicons/page_excel.png',
                ...
```

But how to add this dropdown button to php `$this->_buttons` list?

**Comment by Sogl** [comment]
@daHaimi I'm trying to add my own buttons to GridPanel.

php code:
```php
protected $_buttons = array('add', 'delete', 'xls', 'testbutton');
```

Result:
![image](https://cloud.githubusercontent.com/assets/7556290/13945309/fe46af4a-f057-11e5-9904-e81470a6c733.png)



But I can't add actions, `this.actions` is always `undefined`.
So it can works only with extending `Kwf.Auto.`?
