### ISSUE TITLE
kwf/user/login/activate?code=XXX shows no Password-Auth Method

### ISSUE THREAD

**Issue by Ben-Ho** [koala-framework/koala-framework#446]
User-Activation does not work because Passwort-Auth Methods are not shown if there is any Redirect-Auth-Method

Kwf_Controller_Action_User_BackendActivateController:: 65-72 resets $showPassword to false, even if there are Password-Auth-Methods. This seems ok because if $showPassword is true it's redirected to 'backend-change-password'

But lines 85-100 does not support Password-Auth-Methods.

How should this be solved?

**Comment by Ben-Ho** [comment]
Same with Kwc_User_Activate_Component. Missing password form can be easily solved by setting showPassword to true. But there is still a problem when saving in Kwf_User_Row line 87 where exception is thrown.

**Comment by nsams** [comment]
it sets $showPassword to false only if allowPasswordForUser returns false.

That allows an auth method to disallow a password if the user exists and must be authenticated over that auth method. This is mainly to avoid confused users that don't know if they should set a password or connect their account to a SSO service.
