### ISSUE TITLE
Additional Form Button to modify field values

### ISSUE THREAD

**Issue by daHaimi** [koala-framework/koala-framework#462]
Hi there,

I implemented an additional Button in the Auto-Form to calculate values before saving the form. I need to fill in the values i get back in JSON-format into fields inside a multifield. The problem is, that the findField-Method of the Ext form does not work recursive, so I cannot access the fields.

Is there a way to get all fields by name with any kind of indices to identify?

Thank you in advance

**Comment by nsams** [comment]
There is findByType, findById or findBy, those all work recursively.

**Comment by daHaimi** [comment]
The methods you mentioned are not present in the FormPanel, the BasicForm or the MixedCollection of the items. I can however find the basic fields, but not those who are created using Kwf_Form_Field_MultiFields.
I've seen that BasicForm.setValues works when setting the whole set of variables. But the remaining Problem is, that I need to set only a small set of the values (Marked in the screenshot).
Can I access those fields somehow or do I need to create a full Object for the whole first-level-multifield?
![multifileds-problem](https://cloud.githubusercontent.com/assets/13832589/11926940/01f50038-a7c9-11e5-91b9-f3497ff21e78.png)

**Comment by daHaimi** [comment]
So, I found a Solution. I need to go the getCmp-Way. I must set the Form-ID, so I can access the Elements by using:
```javascript
var timeFields = Ext2.getCmp('RecForm').find('name', 'TimeNeeded');
```
This is because I can access the methods mentioned above if I get the "Component" of the Form only.
