### ISSUE TITLE
Custom AutoGrid button not working properly

### ISSUE THREAD

**Issue by daHaimi** [koala-framework/koala-framework#463]
Hi there,

i used a custom grid button for a barcode scanning dialog. I managed to call the form with the custom parameter "code", which is evaluated on server side. Also, data for the form is loaded and in the response:
```
{data: {RekID: "1", ScanNr: "340050901358", …},
meta: {helpText: null,…},
success: true}
```
but the data is not displayed in the form. Am I missing something? Do i need to call some callback method after data is loaded to tell the form to assign it to the form elements?

My scan method relies on the onAdd action from Kwf.Auto.GridPanel. Maybe the data is not loaded when the onAdd callback is called? When I change the Callback to onEdit, the data is responded no more.

Here is my custom Grid:
```javascript
H3S.GridPanel = Ext2.extend(Kwf.Auto.GridPanel, {
    initComponent: function() {
        this.actions.scan = new Ext2.Action({
            ...
            handler: function() {
                Ext2.MessageBox.show({
                    ...
                    fn: function(btn, code) {
                        if (btn == 'ok') {
                            this.onScan(code);
                        }
                    },
                    ...
                });
                ....
            },
            scope: this
        });

        this.onScan = function(code) {
            this.editDialog = false;
            var foundForm = false;
            this.bindings.each(function(b) {
                if (b.item.getSupportsAdd()) {
                    b.item.enable();
                    b.item.onAdd();
                    foundForm = true;
                    b.item.applyBaseParams({scan: code, meta: true});
                    return false;
                }
            }, this);
            H3S.GridPanel.superclass.onAdd.call(this);
        };
        ...
        H3S.GridPanel.superclass.initComponent.call(this);
    }
});

Ext2.reg('h3s.grid', H3S.GridPanel);
```

**Comment by Sogl** [comment]
@daHaimi , hi!

Maybe it helps you:
https://github.com/koala-framework/koala-framework/issues/302

**Comment by daHaimi** [comment]
Nope, this does not help me.

The Form is loading and called with the correct parameters, even the response seems to be right.
There is just the problem, that te values are not filled into the form fields.

**Comment by nsams** [comment]
onAdd doesn't load a row into the form, it uses defaultValue of form fields only.

I would try this:

- open the form as you do
- make an additional ajax request to get the values
- set them manually

Just make sure you don't do that before the form meta data is loaded - as before that you don't have the fields to fill them.

**Comment by daHaimi** [comment]
Hi nsams,

this worked perfectly. Since I can split the metadata and the data (what uses much more time) I don't have a Problem with making sure that the form is loaded.

Thank you a lot!

**Comment by daHaimi** [comment]
Well... now I've really got that Problem. I cannot use this in another scenario unless I edit one entry before. Is there a best practice to wait for it? I tried to implement callbacks into your grid implementation, but that does not work aswell.

**Comment by nsams** [comment]
Kwf.Auto.FormPanel fires a `renderform` event after meta data is received and the form elements are rendered.
