### ISSUE TITLE
Search in dropdown Kwf_Form_Field_Select

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#465]
Hi!

I want to enable search in dropdown fieild on form like this:
http://dev.sencha.com/deploy/ext-2.3.0/examples/form/combos.html

What I mean:
![image](https://cloud.githubusercontent.com/assets/7556290/11828130/753cec76-a3dd-11e5-99e5-61a5cbb6fddd.png)

Same in kwf-app-demo:
![image](https://cloud.githubusercontent.com/assets/7556290/11828163/c7d73d74-a3dd-11e5-96c2-a9be53beb66a.png)

But I can't find where this country strings live.

How to enable search?

Also how to set `emptyText` option?

**Comment by nsams** [comment]
Country is a `Kwf_Form_Field_SelectCountry` which gets it's values from Zend Framework. If you need custom values just use `Kwf_Form_Field_Select` and specify the requred values using `->setValues`

**Comment by Sogl** [comment]
>If you need custom values just use Kwf_Form_Field_Select and specify the requred values using ->setValues

I'm already use it! 
My question is how to enable searching in dropdown like in countries?

p.s. you close issues very quickly :D

**Comment by nsams** [comment]
I think you have to set

    ->setEditable(true)

Or, instead of using Kwf_Form_Field_Select use Kwf_Form_Field_ComboBox

sorry for closing, please close yourself when your issue is fixed

**Comment by Sogl** [comment]
Works with:
```
->setEditable(true)
```

But how to enable it in this part of code:
```php
protected function _initFields()
    {
        $typeModel = Kwf_Model_Abstract::getInstance('Linkdata');
        $typeSelect = $typeModel->select()->whereEquals('name', 'Позиции на борту')->order('value');

        $positions = new Kwf_Form_Field_Select('positionId', trlKwf('Position'));
        $positions->setValues($typeModel->getRows($typeSelect));
        $positions->setAllowBlank(false);

        $employees = new Kwf_Form_Field_Select('employeeId', trl('Сотрудник'));
        $employees->setValues('/flightplans/flightgroupsfilter/json-data');
        $employees->setAllowBlank(false)->setEditable(true);

        $this->_form->add(new Kwf_Form_Field_FilterField())
        ->setFilterColumn('positionId')
        ->setFilteredField($employees)
        ->setFilterField($positions)
        ->setWidth(400);

        $this->_form->add(new Kwf_Form_Field_TextArea('comment', trlKwf('Comment')))
        ->setHeight(70)
        ->setWidth(400);
    }
```

Second dropbox values fills only after I click on it and I can't search normally:
![animation](https://cloud.githubusercontent.com/assets/7556290/12255723/af463344-b942-11e5-9eb1-415bd0e5dc74.gif)

**Comment by nsams** [comment]
is this your problem probably?

    ->setMinChars(4)

> The minimum number of characters the user must type before autocomplete and typeahead activate (defaults to 4 if remote or 0 if local, does not apply if editable = false)

**Comment by Sogl** [comment]
Thx, it helps a lot! But search now works not from start of value, but in whole word. How to enable search from start?

How it should work:
![0](https://cloud.githubusercontent.com/assets/7556290/12311847/d761f958-baa5-11e5-93a1-c7989a3bfea9.gif)

How it works with filter:
![0_1](https://cloud.githubusercontent.com/assets/7556290/12311857/e1f53b3c-baa5-11e5-87de-298ae00993aa.gif)

**Comment by nsams** [comment]
Seems this is a Ext Combobox feature, or more a store filter feature which enables `anyMatch` by default.

possible workaround 1:

use server side filtering

possible workaround 2:

override doQuery of Combobox (by creating your own combobox class) and replace `q` (the query parameter) with a regexp like  `new RegExp('^' + Ext2.escapeRe(value))`

**Comment by Sogl** [comment]
This is not such a disturbing thing =)
