### ISSUE TITLE
Weird date formatting (MS SQL)

### ISSUE THREAD

**Issue by daHaimi** [koala-framework/koala-framework#469]
Hi There,

i modified the Kwf_Dao to be more flexible and use different db adapters like in the common Zend_Db use.
```php

            $dbConfig = $this->getDbConfig($db);
            if (! array_key_exists('adapter', $dbConfig)) {
                $dbConfig['adapter'] = 'PDO_MYSQL';
            }
            $this->_db[$db] = Zend_Db::factory($dbConfig['adapter'], $dbConfig);
            if (strtoupper($dbConfig['adapter']) == 'PDO_MYSQL') {
                $this->_db[$db]->query('SET names UTF8');
                $this->_db[$db]->query('SET SESSION sql_mode=\'\'');
                if (Kwf_Config::getValue('debug.disableMysqlQueryCache')) {
                    $this->_db[$db]->query('SET SESSION query_cache_type=0');
                }
            }
```
 Now I get a weird Problem:
When I fetch a Datetime-Value from the DB and echo it, I get e.g. "Okt 12 2015 12:00:00:000". When I fetch the value using any DB-Application (tested with VS 2015 and DBeaver), I get the correct values "2015-09-05 00:00:00". Is there any place where some conversion or localization is done on the DB side? I would take a wild guess, that this might happen because of incompatible SQL commands.

**Comment by nsams** [comment]
can you reproduce this problem when using the db adapter only?

**Comment by daHaimi** [comment]
Okay, this is really weird: I just tried to use the Adapter
```php
return $this->getAdapter()->select()->from('ZendeskAPIStat')->query()->fetchAll();
```
And I got the following result:
```
array(1) {
  [0] =>
  array(3) {
    'Id' =>
    string(1) "1"
    'LastUpdate' =>
    string(25) "Jän  1 1970 01:00:00:000"
    'ImportedTickets' =>
    string(1) "0"
  }
}
```
So, this is definitely fetched by adapter only, but localized austrian...
Weird MS SQL actions....
