### ISSUE TITLE
IE works in IE8 mode

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#471]
Hi!

Just found that my IE11 works with KWF in IE8 mode because of this meta-tag:
```html
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8">
```

Emulation tab screen:
![image](https://cloud.githubusercontent.com/assets/7556290/11949801/7606dba8-a8ce-11e5-922e-96f4f85b6031.png)

More info:
https://msdn.microsoft.com/en-us/library/dn255001(v=vs.85).aspx

Files with this line:
```
vendor\koala-framework\koala-framework\views\master.tpl
\views\master.tpl
```

Why this included in the end of 2015? :smile: 
Can I just remove it from my app file?

**Comment by nsams** [comment]
we changed that recently :D

https://github.com/koala-framework/koala-framework/commit/0e7fb5aaecb71c77214e4f91df1c007d45216a76

**Comment by Sogl** [comment]
This cnange is for 3.10, but what about 3.8 and 3.9?

**Comment by nsams** [comment]
that was not pushed - sorry.
