### ISSUE TITLE
How to hide column in Grid?

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#474]
Hi!

I can hide column from grid menu, but how to hide it in code before I show it?

Some info:
https://www.sencha.com/forum/showthread.php?2753-Grid-column-hide&p=245572&viewfull=1#post245572
https://www.sencha.com/forum/showthread.php?71800-Grouping-GridPanel-Hide-groupField-Column

Where I need to put this code?

**Comment by nsams** [comment]
in php add `->setHidden(true)` for the column

**Comment by Sogl** [comment]
So simple. Thx, Niko!
