### ISSUE TITLE
Switching between test and production in config.local.ini

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#482]
Hi!

I save my `config.local.ini` in git with test config lines. But after `git pull` on production server I have config-file with test server and need to overwrite it with production lines every pull.... how to keep both server info in one file and switch between config sections on machines?
Something like `php bootstrap.php -config=production` and `php bootstrap.php -config=test`.

I see this and can't find answer:
http://www.koala-framework.org/documentation/kwf_general_features/config

**Comment by nsams** [comment]
I think `config_section` file is what you are looking for. (see "Used config section" in the page you linked)

And don't put `config.local.ini` into git, instead write that into `config.ini`. local.ini is for database passwords if you don't want that in git.

**Comment by Sogl** [comment]
>I think config_section file is what you are looking for. (see "Used config section" in the page you linked)

So...I need to create `config_section` file and put line `production` on production server and `development` on dev machine?

**Comment by nsams** [comment]
I extended the documentation, see last paragraph:
http://www.koala-framework.org/documentation/kwf_general_features/config

**Comment by Sogl** [comment]
## Before

config.ini:
```
[production]
...
...
```

config.local.ini:
```
[production]
...
...
```

## After

config.ini:
```
[production]
...
...
[production : development]
...
...empty because the same as in production...
```

config.local.ini:
```
[production]
...
...
[development]
...
...
```
config_section:
```
development
```

Right? Where to put `kwfConfigSection`?

**Comment by nsams** [comment]
add to config.ini development section. And it needs to be `[development : production]` (section development inherits production)

and you don't need production + development in config.local.ini as you won't have it under source control anyway. (it doesn't harm though)

**Comment by Sogl** [comment]
## Now

config.ini:
```ini
[production]
...
...
[development : production]
kwfConfigSection = development
```

config.local.ini:
```ini
[production]
...
...
[development : production]
...override db settings...
...
```
config_section:
```
development
```

Error:
```
exception 'Zend_Config_Exception' with message 'Section 'development' cannot be found in vendor/koala-framework/koala-framework/config.ini' in C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Config\Ini.php:151
Stack trace:
#0 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config\Web.php(117): Zend_Config_Ini->__construct('vendor/koala-fr...', 'development', Array)
#1 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Config\Web.php(42): Kwf_Config_Web->__construct('development')
#2 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Registry.php(11): Kwf_Config_Web::getInstance()
#3 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Registry.php(150): Kwf_Registry->offsetGet('config')
#4 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Registry.php(27): Zend_Registry::get('config')
#5 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Registry.php(150): Kwf_Registry->offsetGet('userModel')
#6 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(153): Zend_Registry::get('userModel')
#7 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(78): Kwf_Controller_Action->_getUserRole()
#8 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Action.php(21): Kwf_Controller_Action->preDispatch()
#9 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Dispatcher\Standard.php(308): Kwf_Controller_Action->dispatch('indexAction')
#10 C:\OpenServer\domains\aviashelf\vendor\koala-framework\zendframework1\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#11 C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Controller\Front.php(140): Zend_Controller_Front->dispatch(Object(Kwf_Controller_Request_Http), Object(Kwf_Controller_Response_Http))
#12 C:\OpenS
```

**Comment by nsams** [comment]
Koala needs to know which section to use from vendor/koala-framework/koala-framework/config.ini. And exactly that you can specify using kwfConfigSection. As there is no development section you get the error `'Section 'development' cannot be found in vendor/koala-framework/koala-framework/config.ini'`

Instead use:
kwfConfigSection = production

**Comment by Sogl** [comment]
@nsams А bit confusing system but it's working now! Big thanks!

Can you say where you store config files for projects and different servers if not in git? :relieved:

**Comment by nsams** [comment]
we have everything except database connection in config.ini. When using different servers that need different config we simply create a new config section per server.

**Comment by daHaimi** [comment]
Hi, i got the same Problem, but I still don't understand waht exactly the problem is...
I don't use the config.local.ini, but only the config.ini:
```ini
[production]
......configs.....

[local : production]
....overrides....
```
my `config_section` contains `local` and still I get the error:
> PHP Fatal error:  Uncaught exception 'Kwf_Exception' with message 'Add either 'local' to kwf/config.ini or set kwfConfigSection in web config.ini' in /var/www/.../vendor/koala-framework/koala-framework/Kwf/Config/Web.php:101
When I add `kwfConfigSection = production` to my local section, I get:
> PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Parent section 'local' cannot be found' in /var/www/.../vendor/koala-framework/zendframework1/library/Zend/Config/Ini.php:258
I hope you can help me with this one.

**Comment by nsams** [comment]
that means you have somewhere a ini section that inherits from local but local is not defined in this file. Inheriting works only for the current file.

When you post the complete backtrace we can probably see what file this is.
