### ISSUE TITLE
Custom Panels with binding

### ISSUE THREAD

**Issue by daHaimi** [koala-framework/koala-framework#496]
Hi there,

I need another customization and have no idea how to approach it:
I need a custom panel (Extending `Kwf.Binding.AbstractPanel`) to load Data with the bound params from a custom action. Since I want to trigger it from a grid row click, I think using the framework's internals.

But: how can I catch the rowclick event in my custom panel to handle the data?

**Comment by nsams** [comment]
if you bind the panel to a grid it get's baseParams automatically set - containing the id of the selected row.

You can also listen `grid.on('rowselect', ...` and so everything manually instead of using the bindings. You can also use bindings and change additional stuff in rowselect.

**Comment by daHaimi** [comment]
Thanks, that worked!
