### ISSUE TITLE
Form Field default values not displayed

### ISSUE THREAD

**Issue by daHaimi** [koala-framework/koala-framework#497]
Hi there, I am trying to build a Form with some fields predefined by the underlying database.
I am setting the values using `$element->setValue(...);` And the value is sent with the meta data:
```json
{
    decimalPrecision: 2
    decimalSeparator: ","
    fieldLabel: "Some-Nr."
    inputType: "text"
    labelSeparator: ":"
    minValue: 0
    name: "SomeNr"
    readOnly: true
    value: 7332
    width: 300
    xtype: "numberfield"
}
```
Unfortunately, it dowas not render to HTML:
```html
<input type="text" size="20" autocomplete="off" id="ext2-comp-1031" name="SomeNr" class=" x2-form-text x2-form-field x2-form-num-field " readonly="" style="width: 292px;">
```
Is there some kind of postprocessing the empty Form in case of a new entry which overwrites my default value?

**Comment by daHaimi** [comment]
Addition: It also does not work without readOnly option.

**Comment by nsams** [comment]
I think `->setDefaultValue` is what you are looking for

**Comment by daHaimi** [comment]
Yes, that solved it. thank you. I think solving of #498 would improve the workflow with these questions ;-)
I'll do my very best
