### ISSUE TITLE
How to disable DateField editable

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#504]
Hi!

How to switch off DateField editable like in TextField?
I tried with `setReadOnly(true)`, `setEditable(false)` and it's not working.

**Comment by nsams** [comment]
That needs to be supported by Ext. If it doesn't work it is probably not supported...

What about using a TextField instead? Or a ShowField?

**Comment by Sogl** [comment]
>What about using a TextField instead? Or a ShowField?
I need to use custom date format `d.m.Y`, that can't supported by these fields.

I did in this way:
```
    $personal->fields->add(new Kwf_Form_Field_DateField('birthDate', trl('Дата рождения')))
                ->setLabelStyle('font-weight:bold;')
                ->setHideTrigger(true)
                ->setReadOnly(true);
```

**Comment by nsams** [comment]
What koala does is just passing those options to extjs. If you pass readOnly and ext doesn't support that it won't work.

If you problem is the date format - easy to solve that:

    $personal->fields->add(new Kwf_Form_Field_ShowField('birthDate', trl('Дата рождения')))
                ->setLabelStyle('font-weight:bold;')
                ->setTpl('{value:localizedDate}');

setTpl support any XTemplate and localizedDate could be any Ext2.util.Format renderer - see extjs and Kwf_js/Renderer.js

**Comment by Sogl** [comment]
Thanks. That working fine now.
