### ISSUE TITLE
Third nesting controllers folder level 404 error

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#505]
Hi!

I created a 3rd folder level with my 4 controllers (`D` - new folder 3rd level):
![image](https://cloud.githubusercontent.com/assets/7556290/13798992/350824dc-eb67-11e5-9011-5057fd140f1b.png)

Controller class name changed:
```php
class D_Links_LinksController extends Kwf_Controller_Action_Auto_Grid
```

Acl:
```php
$this->addResource(new Kwf_Acl_Resource_MenuUrl('links_index', array('text'=>trlKwfStatic('General'), 'icon'=>'book2.png'), '/d/links/links'), 'default_menuitem');
		
$this->addResource(new Zend_Acl_Resource('links_links'), 'links_index');
$this->addResource(new Zend_Acl_Resource('links_link'), 'links_index');
$this->addResource(new Zend_Acl_Resource('links_linkdata'), 'links_index');
$this->addResource(new Zend_Acl_Resource('links_linkdataentry'), 'links_linkdata');

$this->allow(array('admin', 'power'), 'links_index');
```

And result:
```
404 - File not found

The requested address "/d/links/links" is not found.
```

I did `clear-cache` and `build` many times. Also tried to change all related ACL resource names and controller URLs in js.

What's wrong with it?

**Comment by nsams** [comment]
That is not supported by the default configuration of Zend_Controller_Front. You'll have to
- add a module directroy
- add a route

All that is not related to koala framework (which only adds a few default routes) - it's Zend Framework Controller. (Sometimes not so easy to configure I have to admit...)

**Comment by Sogl** [comment]
Sad
