### ISSUE TITLE
How to enable superuser role?

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#506]
Hi!

I'm from this article:
http://www.koala-framework.org/documentation/kwf_general_features/acl

As I can see, some roles are default, but how to set `superuser`?
![image](https://cloud.githubusercontent.com/assets/7556290/13800495/72223034-eb75-11e5-8f5c-b6f164564ec1.png)

**Comment by nsams** [comment]
Superuser is in `Kwf_Acl_Component`. When you are using `Kwf_Acl` you don't have superuser.

**Comment by Sogl** [comment]
What the difference between them? What `Kwf_Acl_Component` is doing?

**Comment by nsams** [comment]
That adds a few default resources (and roles) useful when using Components (Kwc)

If you don't have components `Kwf_Acl` is for you.

**Comment by Sogl** [comment]
Ok. I created +1 role to solve my needs.
