### ISSUE TITLE
500 Internal Server Error instead of specific error

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#523]
Hi!

Now in every exception I see 500 server error instead of specific. Responce:
```
<html>
    <head>
        <title>500 Internal Server Error</title>
    </head>
    <body>
        <h1>Error</h1>

                    An Error ocurred. Please try again later.
                    </body>
</html>
```

I didn't touch `.htaccess` file, only `composer update`.

What could cause this?

**Comment by nsams** [comment]
Usually verbose error logging is enabled using `debug.error.log = false` in config.ini

**Comment by Sogl** [comment]
You right, was set to `true`. Solved.
