### ISSUE TITLE
Saving time values as integer

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#527]
Hello!

My TIME values (hours:minutes) in DB in most situations is greater than `838:59:59` limit that described here:
https://dev.mysql.com/doc/refman/5.7/en/time.html

>By default, values that lie outside the TIME range but are otherwise valid are clipped to the closest endpoint of the range. For example, '-850:00:00' and '850:00:00' are converted to '-838:59:59' and '838:59:59'.

So I started to use INT instead of TIME and have some troubles:
1.. I need to convert time before write and before show. I use this code in Row controller:
```php
public function __get($name)
    {
        if ($name === 'workTimePPR')
        {
            $timeInMinutes = parent::__get('workTimePPR');
            return str_pad ((int)($timeInMinutes / 60), 2, "0", STR_PAD_LEFT) . ':' . 
str_pad (($timeInMinutes % 60), 2, "0", STR_PAD_LEFT);
        }
        return parent::__get($name);
    }

public function __set($name, $value)
    {
        if ($name === 'workTimePPR')
        {
            $timeParts = explode(":", $value);

            $hours = intval($timeParts[0]);
            $minutes = 0;

            if (count($timeParts) > 1)
            {
                $minutes = intval($timeParts[1]);
            }

            return parent::__set('workTimePPR', $hours * 60 + $minutes);
        } 
        return parent::__set($name, $value);
    }
```

Is it correct place for modification? Maybe I can use built-in MySQL time functions somewhere?

2.. I need to show value in form for user edit. I use 
```php
$this->_form->add(new Kwf_Form_Field_TextField('workTimePPR', trl('Наработка ППР')))
            ->setWidth(400);
```

The problem is that the user can type anything in the field, letters for example. What type of Kwf_Form_Field I need to use?

3.. I need to show value in Grid. It's impossible with this code:
```php
$this->_columns->add(new Kwf_Grid_Column('workTimePPR', trl('Наработка ППР'), 50));
```

If I have value `10:01`, than I see `10` in the column. How to solve this problem?

**Comment by nsams** [comment]
> 1.. I need to convert time before write and before show. I use this code in Row controller:

yes, that works. However I would use a different field name and create a "Virtual" column that way.

> 2.. I need to show value in form for user edit. I use

you can do that using a custom vtype which also includes a Mask (list of allowed characters to type). See Kwf_js/Form/BasicForm.js, we even have a time vtype there, but that doesn't allow >99h so you need your own. Also see http://docs.sencha.com/extjs/2.3.0/#!/api/Ext.form.TextField

> 3.. I need to show value in Grid. It's impossible with this code:

that is because the type of the column is an integer. Either you do what I wrote in (1) - so the new virtual coumn isn't an integer, or you manually override the type by overriding getColumnType in the model.

**Comment by nsams** [comment]
> Like this?

yes, that should work.

**Comment by Sogl** [comment]
Solved. Thanks.
If I have any questions I'll put it here :wink:
