### ISSUE TITLE
ShowSelect 3.8 fix not merged into 3.9

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#568]
Hi!

Today I found an old bug in 3.9 KWF version:
```
Fatal error:  Call to a member function __toString() on a non-object in <b>/var/www/puls/vendor
/koala-framework/koala-framework/Kwf/Form/Field/ShowSelect.php on line 42
```

It was fixed in 3.8 branch by https://github.com/koala-framework/koala-framework/pull/519 but still isn't fixed in 3.9.

Compare:
https://github.com/koala-framework/koala-framework/blob/3.8/Kwf/Form/Field/ShowSelect.php#L38
https://github.com/koala-framework/koala-framework/blob/3.9/Kwf/Form/Field/ShowSelect.php#L38

**Comment by nsams** [comment]
done 92254f4018ae170bacc5baa07c6c14096abe0f72

**Comment by Sogl** [comment]
:+1:
