### ISSUE TITLE
EXISTS/NOT EXISTS sql query with KWF/ZF

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#569]
Hi!

How to build `EXISTS/NOT EXISTS` query with KWF?
I need it for use `kwf_uploads` model functions. Direct queries do not allow it.

I tried this solution: 
http://stackoverflow.com/a/11789659/4827198

Doesn't work. Also nothing about it in KWF sources.

**Comment by nsams** [comment]
You have a table with a foreign key pointing to kwf_uploads? What exactly do you want to look for?

**Comment by Sogl** [comment]
My sql is:
```sql
SELECT id
FROM kwf_uploads AS u
WHERE NOT EXISTS (SELECT NULL FROM documents WHERE u.id = picture_id )
...
```

But I don't know how to build such type of query (`WHERE NOT EXISTS`).
This type of query is much quicker than `JOINS` + `UNIONS`.

**Comment by nsams** [comment]
That is not possible.

If you need optimized sql queries you have to write them manually - like you did.
