### ISSUE TITLE
How to set checkbox to checked state?

### ISSUE THREAD

**Issue by Sogl** [koala-framework/koala-framework#599]
I have checkbox in the form:
```php
 $this->_form->add(new Kwf_Form_Field_Checkbox('active', trl('Активен')));
```

I want to render it alredy checked:
http://docs.sencha.com/extjs/2.3.0/#!/api/Ext.form.Checkbox

I tried some methods without success:
```php
//1
->setProperty('checked', true);
//2
->setProperty('checked', 1);
//3
->setChecked(true);
//
->setChecked(1);
```

How to do this?

**Comment by nsams** [comment]
The checked state of a checkbox is like the value of a textfield. It is loaded from the row the AutoForm is editing.

When you create a new entry, the default value from the form is used - change it by using setDefaultValue(true)

**Comment by Sogl** [comment]
Works, thx!

But why this line not working:
```php
->setProperty('checked', true);
```
?

In other situations it works fine.

**Comment by nsams** [comment]
> But why this line isn't working:

Because it gets overwritten by the value loaded into the form.
